#!/bin/sh
# Install or update the multiSSH proxy on this machine. Run as root.
#
# Idempotent: a second run replaces the binary and the agent builds and leaves
# the authority key, the host key, the ledgers and the unit's configuration
# exactly as they were. It is safe to run against a live proxy.
#
# Normally invoked by deploy/push.sh from a development machine rather than by
# hand, but it takes no arguments that could not be typed:
#
#   sh install-proxy.sh --public-url https://multissh.example.com --user-addr :2022
#
# Expects multissh-proxy and dist/ beside it, which is what push.sh ships.
set -eu

SRC=$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd)

USER_NAME=${MULTISSH_SERVICE_USER:-multissh}
STATE=${MULTISSH_STATE:-/var/lib/multissh}
BIN=${MULTISSH_BIN:-/usr/local/bin/multissh-proxy}
UNIT=/etc/systemd/system/multissh-proxy.service

PUBLIC_URL=${MULTISSH_PUBLIC_URL:-}
USER_ADDR=${MULTISSH_USER_ADDR:-:2022}
AGENT_ADDR=${MULTISSH_AGENT_ADDR:-127.0.0.1:8080}
EXTRA_ARGS=${MULTISSH_EXTRA_ARGS:-}

while [ $# -gt 0 ]; do
    case "$1" in
        --public-url) PUBLIC_URL=$2; shift 2 ;;
        --user-addr)  USER_ADDR=$2;  shift 2 ;;
        --agent-addr) AGENT_ADDR=$2; shift 2 ;;
        --extra-args) EXTRA_ARGS=$2; shift 2 ;;
        -h|--help)
            sed -n '2,14p' "$0" | sed 's/^# \{0,1\}//'
            exit 0 ;;
        *) echo "unknown option: $1" >&2; exit 2 ;;
    esac
done

die() { echo "error: $*" >&2; exit 1; }
[ "$(id -u)" = 0 ] || die "run this as root"
[ -f "$SRC/multissh-proxy" ] || die "no multissh-proxy beside this script (expected $SRC/multissh-proxy)"

FIRST_RUN=
[ -f "$UNIT" ] || FIRST_RUN=1
if [ -n "$FIRST_RUN" ] && [ -z "$PUBLIC_URL" ]; then
    die "--public-url is required on a first install: the proxy bakes it into the installer it serves"
fi

# ---------------------------------------------------------------- account

# A system account with no login shell and no home: the proxy needs to read its
# own directory and nothing else on the machine.
if ! id "$USER_NAME" >/dev/null 2>&1; then
    echo "creating system user $USER_NAME"
    useradd --system --home-dir "$STATE" --shell /usr/sbin/nologin "$USER_NAME" 2>/dev/null ||
        useradd --system --home-dir "$STATE" --shell /sbin/nologin "$USER_NAME"
fi

mkdir -p "$STATE/dist"

# The proxy treats a missing users file as a configuration error and exits, so
# it has to exist before the service is started or the first install would
# crash-loop and this script would report a proxy that will not run. Empty is
# the right starting state: it means nobody can use the proxy yet, while agents
# can still register.
if [ ! -f "$STATE/users_authorized_keys" ]; then
    cat > "$STATE/users_authorized_keys" <<'EOF'
# Public keys allowed to use this proxy, one per line, ordinary
# authorized_keys format. Until one is here, nobody can connect.
#
#   ssh-ed25519 AAAA... you@yourlaptop
EOF
fi

chown -R "$USER_NAME:$USER_NAME" "$STATE"
chmod 0750 "$STATE"
chmod 0640 "$STATE/users_authorized_keys"

# ---------------------------------------------------------------- binaries

# Replaced by rename for the same reason the agent's is: a running executable
# cannot be written in place, and stopping the proxy first would drop every
# agent for the length of a copy rather than the length of a restart.
install_file() { # install_file SRC DEST MODE
    cp -p "$1" "$2.new"
    chmod "$3" "$2.new"
    mv "$2.new" "$2"
}

BINARY_CHANGED=1
if [ -f "$BIN" ] && cmp -s "$SRC/multissh-proxy" "$BIN"; then
    BINARY_CHANGED=
fi
if [ -n "$BINARY_CHANGED" ]; then
    echo "installing proxy binary to $BIN"
    install_file "$SRC/multissh-proxy" "$BIN" 0755
else
    echo "proxy binary unchanged"
fi

DIST_CHANGED=
if [ -d "$SRC/dist" ]; then
    for build in "$SRC"/dist/*; do
        [ -f "$build" ] || continue
        name=$(basename "$build")
        if ! cmp -s "$build" "$STATE/dist/$name"; then
            DIST_CHANGED=1
            install_file "$build" "$STATE/dist/$name" 0755
            echo "  agent build $name"
        fi
    done
    chown -R "$USER_NAME:$USER_NAME" "$STATE/dist"
fi
[ -n "$DIST_CHANGED" ] || echo "agent builds unchanged"

# ---------------------------------------------------------------- unit

# Written only on a first install. Re-running must not quietly revert a unit
# someone edited on the server, which is where the real flags tend to end up.
if [ -n "$FIRST_RUN" ]; then
    echo "writing $UNIT"
    cat > "$UNIT" <<EOF
# multiSSH proxy. Generated by install-proxy.sh; edit freely, re-running the
# installer will not overwrite it.
#
# Back up $STATE/proxy_ca_key and $STATE/revoked_keys. The first is what the
# whole system is recoverable from; the second is the only file whose loss
# undoes work silently, by un-revoking every barred machine.
[Unit]
Description=multiSSH proxy
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=$USER_NAME
Group=$USER_NAME
WorkingDirectory=$STATE
ExecStart=$BIN \\
    -user-addr $USER_ADDR \\
    -agent-addr $AGENT_ADDR \\
    -public-url $PUBLIC_URL \\
    -dist $STATE/dist$( [ -n "$EXTRA_ARGS" ] && printf ' \\\n    %s' "$EXTRA_ARGS" )
# SIGHUP re-reads the agent builds in place, so shipping a new agent costs
# nobody their connection.
ExecReload=/bin/kill -HUP \$MAINPID
Restart=always
RestartSec=5

# Each agent is one file descriptor, so the usual 1024 would cap this at
# roughly a thousand targets.
LimitNOFILE=65535

NoNewPrivileges=yes
ProtectSystem=strict
ProtectHome=yes
PrivateTmp=yes
PrivateDevices=yes
ReadWritePaths=$STATE

[Install]
WantedBy=multi-user.target
EOF
    systemctl daemon-reload
    systemctl enable multissh-proxy
fi

# Binding a port below 1024 as a non-root user needs the capability granted
# explicitly. Checked every run, since the port can change in the unit.
if grep -q -- "-user-addr :\([0-9]\|[1-9][0-9]\|[1-9][0-9][0-9]\|10[0-1][0-9]\|102[0-3]\)\b" "$UNIT" 2>/dev/null; then
    if ! grep -q AmbientCapabilities "$UNIT"; then
        echo "note: the user listener is on a privileged port but the unit grants no"
        echo "      CAP_NET_BIND_SERVICE. Add to [Service]:"
        echo "        AmbientCapabilities=CAP_NET_BIND_SERVICE"
        echo "        CapabilityBoundingSet=CAP_NET_BIND_SERVICE"
    fi
fi

# ---------------------------------------------------------------- start

if [ -n "$FIRST_RUN" ]; then
    systemctl start multissh-proxy
    echo
    echo "  installed and running. It is not useful yet -- three things left:"
    echo
    echo "    1. authorise your own key, or nobody can connect:"
    echo "         echo 'ssh-ed25519 AAAA... you' >> $STATE/users_authorized_keys"
    echo "         systemctl reload multissh-proxy   # no agent loses its connection"
    echo
    echo "    2. create an enrolment password, or no machine can enrol:"
    echo "         sudo $BIN -passwords $STATE/enrol_passwords.json \\"
    echo "              -add-password laptops -password-validity 720h"
    echo "         sudo chown $USER_NAME:$USER_NAME $STATE/enrol_passwords.json"
    echo
    echo "       (as root, not as $USER_NAME: the password is read from your"
    echo "        terminal, and $USER_NAME cannot open a terminal owned by you)"
    echo
    echo "    3. take the authority's public key back to your own machine:"
    echo "         sudo -u $USER_NAME $BIN -ca-key $STATE/proxy_ca_key -show-ca"
    echo
    echo "       and put it in ~/.ssh/known_hosts there as:"
    echo "         @cert-authority [<host>]:<port> ssh-ed25519 AAAA..."
    echo
elif [ -n "$BINARY_CHANGED" ]; then
    # A new binary needs a real restart. Agents reconnect on their own within
    # a couple of seconds, so this is brief rather than free.
    echo "restarting (new binary; agents will reconnect)"
    systemctl restart multissh-proxy
elif [ -n "$DIST_CHANGED" ]; then
    # Only the agent builds changed, so the running proxy just re-reads them.
    echo "reloading (agent builds only; no agent loses its connection)"
    systemctl reload multissh-proxy
else
    echo "nothing to do"
fi

systemctl is-active --quiet multissh-proxy && echo "proxy is running" || die "proxy is not running: journalctl -u multissh-proxy"
