# multiSSH agent installer for Windows.
#
# Generated by the proxy, which bakes in its own certificate authority and
# address below, so the agent pins the right authority from its first connect.
#
# Registered as a scheduled task at boot rather than a service: a proper
# Windows service needs a service-control handler in the binary. The task is
# set to restart on failure and to have no execution time limit, so the gap
# between this and a service is smaller than it looks.
#
# Recommended, because it survives an error without closing your window and
# needs no execution-policy change:
#
#   irm https://proxy/install.ps1 -OutFile $env:TEMP\multissh-install.ps1
#   powershell -ExecutionPolicy Bypass -File $env:TEMP\multissh-install.ps1
#
# Elevated installs run as SYSTEM from a boot trigger; unelevated ones run as
# you from a logon trigger. -Scope system|user forces either. Both can be
# installed side by side.
#
# Options need the file form, or the scriptblock form -- piping into iex gives
# no way to pass arguments:
#
#   & ([scriptblock]::Create((irm https://proxy/install.ps1))) -Uninstall

[CmdletBinding()]
param(
    [switch]$Uninstall,
    [switch]$Update,
    [switch]$Rollback,
    [switch]$Reenroll,
    [switch]$Yes,
    [string]$Name,
    [string]$Password,
    [ValidateSet('system', 'user')]
    [string]$Scope
)

$ErrorActionPreference = 'Stop'

$BaseUrl  = '__BASE_URL__'
$Proxies  = '__PROXIES__'
$CaKey    = '__CA__'
$Version  = '__VERSION__'
$Hashes   = '__HASHES__'

# Two scopes, as on Linux.
#
#   system  runs as SYSTEM from a boot trigger, so the machine is reachable
#           before anyone logs in. Needs an elevated shell.
#   user    runs as you from a logon trigger, with your profile, your PATH and
#           your per-user applications -- winget among them. Needs no
#           administrator, and is not reachable while you are logged out.
#
# Both can be installed at once, and usefully so: the SYSTEM one is the rescue
# path, the user one is the comfortable one. They keep separate directories,
# separate keys and separate scheduled tasks, so neither can disturb the other.
$SystemInstallDir = Join-Path $env:ProgramFiles 'multiSSH'
$SystemStateDir   = Join-Path $env:ProgramData 'multiSSH'
$UserInstallDir   = Join-Path $env:LOCALAPPDATA 'multiSSH'
$UserStateDir     = Join-Path $UserInstallDir 'state'

# ------------------------------------------------------------- functions
#
# All of them, before anything that runs. PowerShell executes a function
# definition as a statement, so a function called from a block placed above its
# definition is simply not defined yet -- which is how -Rollback came to fail
# with "the term 'Restart-Agent' is not recognized".

# Write-Error would be turned into a terminating error by the preference above,
# so the exit code would come from the error rather than from here.
function Die($m) {
    Write-Host "error: $m" -ForegroundColor Red
    exit 1
}

function Test-Admin {
    $id = [Security.Principal.WindowsIdentity]::GetCurrent()
    $p  = New-Object Security.Principal.WindowsPrincipal($id)
    return $p.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
}

function Get-Manifest {
    if (Test-Path $Manifest) { return Get-Content $Manifest -Raw | ConvertFrom-Json }
    return $null
}

function Stop-Agent {
    Stop-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue
}

function Remove-AgentTask {
    Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false -ErrorAction SilentlyContinue
}

# Start-Agent registers the task and starts it.
#
# Register-ScheduledTask rather than schtasks.exe: schtasks caps the whole /TR
# command line at 261 characters and the real argument list here is over 350,
# so it failed outright -- at the very last step, on a machine that had already
# enrolled. It also cannot express restart-on-failure, and leaves the default
# three-day execution time limit in place, which would have killed the agent
# after three days with nothing to say why.
function Start-Agent($argline) {
    $action = New-ScheduledTaskAction -Execute $Binary -Argument $argline
    $settings = New-ScheduledTaskSettingsSet `
        -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries -StartWhenAvailable `
        -MultipleInstances IgnoreNew `
        -ExecutionTimeLimit ([TimeSpan]::Zero) `
        -RestartCount 3 -RestartInterval (New-TimeSpan -Minutes 1)

    if ($Scope -eq 'system') {
        # At boot, as SYSTEM: reachable before anyone logs in, which is the
        # whole reason a rescue tool wants this scope.
        $trigger   = New-ScheduledTaskTrigger -AtStartup
        $principal = New-ScheduledTaskPrincipal -UserId 'SYSTEM' `
            -LogonType ServiceAccount -RunLevel Highest
    } else {
        # At logon, as you. Registering a task for yourself needs no
        # administrator, and the agent then has your profile, your PATH and
        # your per-user applications.
        $me = "$env:USERDOMAIN\$env:USERNAME"
        $trigger   = New-ScheduledTaskTrigger -AtLogOn -User $me
        $principal = New-ScheduledTaskPrincipal -UserId $me `
            -LogonType Interactive -RunLevel Limited
    }

    Register-ScheduledTask -TaskName $TaskName -Action $action -Trigger $trigger `
        -Principal $principal -Settings $settings -Force | Out-Null
    Start-ScheduledTask -TaskName $TaskName
}

function Restart-Agent($argline) {
    Stop-Agent
    Start-Agent $argline
}

function Expected-Hash {
    foreach ($pair in $Hashes -split ' ') {
        $p, $h = $pair -split ':', 2
        if ($p -eq 'windows-amd64') { return $h }
    }
    return $null
}

# Replaces the agent without stopping it first, matching install.sh.
#
# Windows will not let a running .exe be overwritten, but it will let one be
# renamed. So the outgoing binary is renamed aside and the new one takes its
# place; the running process is undisturbed and only the restart at the end
# interrupts anything. An update driven over the agent's own tunnel therefore
# cannot leave the machine with no agent at all.
function Download-Binary {
    $want = Expected-Hash
    if (-not $want) { Die 'the proxy has no agent build for windows-amd64' }
    New-Item -ItemType Directory -Force -Path $InstallDir | Out-Null
    $new = "$Binary.new"
    Write-Host "downloading agent $Version for windows-amd64"
    Invoke-WebRequest -Uri "$BaseUrl/dist/windows-amd64" -OutFile $new -UseBasicParsing
    $got = (Get-FileHash $new -Algorithm SHA256).Hash.ToLower()
    if ($got -ne $want.ToLower()) {
        Remove-Item $new -Force
        Die "checksum mismatch: expected $want, got $got"
    }
    if (Test-Path $Binary) {
        Remove-Item -Force "$Binary.prev" -ErrorAction SilentlyContinue
        Move-Item -Force $Binary "$Binary.prev"
    }
    Move-Item -Force $new $Binary
}

# Key files must be plain ASCII. Set-Content's default encoding differs between
# Windows PowerShell and PowerShell 7, and a byte-order mark in front of an
# ssh-ed25519 line makes the agent fail to parse its own certificate with a
# message that points nowhere near the cause.
function Write-KeyFile($path, $content) {
    Set-Content -Path $path -Value $content -Encoding ascii -NoNewline
}

# ------------------------------------------------------------- scope

$elevated = Test-Admin

# Scope follows elevation, exactly as install.sh follows uid: an elevated shell
# installs for the machine, anyone else installs for themselves. -Scope forces
# either.
#
# Deliberately not cleverer than that. An earlier version also consulted which
# manifests already existed, which produced a dead end -- an unelevated run on a
# machine that already had a system install resolved to "system" and then
# refused itself, when what the person plainly wanted was their own.
if (-not $Scope) {
    if ($elevated) { $Scope = 'system' } else { $Scope = 'user' }
}

if ($Scope -eq 'system') {
    if (-not $elevated) {
        Die 'a system install needs an elevated PowerShell (Run as Administrator), or pass -Scope user to install for yourself'
    }
    $InstallDir = $SystemInstallDir
    $StateDir   = $SystemStateDir
    $TaskName   = 'multiSSH agent'
} else {
    $InstallDir = $UserInstallDir
    $StateDir   = $UserStateDir
    # A distinct name: scheduled tasks share one namespace across the machine,
    # so a user install must not collide with the SYSTEM one. Both are meant to
    # be able to exist at once.
    $TaskName   = "multiSSH agent ($env:USERNAME)"
}
$Binary   = Join-Path $InstallDir 'multissh-agent.exe'
$Manifest = Join-Path $StateDir 'manifest.json'

# ------------------------------------------------------------- uninstall

if ($Uninstall) {
    $m = Get-Manifest
    if (-not $m) { Die "nothing installed here (no $Manifest)" }
    Write-Host "will remove:"
    Write-Host "  $($m.binary)"
    Write-Host "  $($m.state)  (identity key, host key, certificate)"
    Write-Host "  scheduled task '$TaskName'"
    if (-not $Yes) {
        $c = Read-Host 'remove, including the keys? [y/N]'
        if ($c -notmatch '^[yY]') { Write-Host 'cancelled'; exit 0 }
    }
    # Ordered so that an uninstall driven over the agent's own tunnel finishes:
    # ending the task kills this script with it, so everything that can be done
    # while the agent still runs is done first. Windows refuses to delete a
    # running .exe but allows it to be renamed, so the binary is moved aside
    # and only then deleted.
    Remove-AgentTask
    Remove-Item -Recurse -Force $m.state -ErrorAction SilentlyContinue
    if (Test-Path $m.binary) {
        Move-Item -Force $m.binary "$($m.binary).removing" -ErrorAction SilentlyContinue
    }
    Remove-Item -Force "$($m.binary).prev", "$($m.binary).new" -ErrorAction SilentlyContinue
    Write-Host 'removed.'
    Stop-Agent
    Remove-Item -Recurse -Force $InstallDir -ErrorAction SilentlyContinue
    exit 0
}

# ------------------------------------------------------------- rollback

if ($Rollback) {
    $m = Get-Manifest
    if (-not $m) { Die "nothing installed here (no $Manifest)" }
    if (-not (Test-Path "$Binary.prev")) { Die "no previous binary saved at $Binary.prev" }
    Copy-Item -Force "$Binary.prev" "$Binary.rollback"
    Move-Item -Force "$Binary.rollback" $Binary
    # The recorded version no longer describes what is on disk, so clear it or
    # the next -Update would decide there was nothing to do.
    $m.version = 'rolled-back'
    $m | ConvertTo-Json | Set-Content $Manifest
    Restart-Agent $m.args
    Write-Host 'rolled back to the previous binary; run -Update to go forward again'
    exit 0
}

# ------------------------------------------------------------- update

# This copy has the proxy's version frozen into it from install time and the
# manifest holds that same value, so comparing them here would always report
# "already current". Fetch what the proxy is serving now and hand over to it.
#
# Run as a scriptblock rather than as a file: executing a downloaded .ps1 is
# subject to the execution policy, which on a default Windows install refuses
# it -- and the whole point of the piped installer is that it does not need one
# changed.
if ($Update -and -not $env:MULTISSH_NO_REFETCH -and (Test-Path $Manifest)) {
    $fetched = $null
    try {
        $fetched = (Invoke-WebRequest -Uri "$BaseUrl/install.ps1" -UseBasicParsing).Content
    } catch {
        Write-Host "could not reach $BaseUrl; continuing with this copy"
    }
    if ($fetched) {
        $env:MULTISSH_NO_REFETCH = '1'
        try {
            & ([scriptblock]::Create($fetched)) -Update -Yes:$Yes
        } finally {
            Remove-Item Env:\MULTISSH_NO_REFETCH -ErrorAction SilentlyContinue
        }
        exit 0
    }
}

$existing = Get-Manifest
if ($existing -and -not $Reenroll) {
    if (-not $Update) {
        Write-Host "already installed here ($($existing.canonical)); updating instead."
        Write-Host "pass -Reenroll to discard that identity and enrol afresh."
    }
    if ($existing.ca -ne $CaKey) { Die 'this proxy has a different authority than the one enrolled with; refusing' }
    if ($existing.version -eq $Version) { Write-Host "already current ($Version)"; exit 0 }
    Download-Binary
    $existing.version = $Version
    $existing | ConvertTo-Json | Set-Content $Manifest
    Restart-Agent $existing.args
    Write-Host "updated to $Version; keys and certificate untouched"
    exit 0
}

# ------------------------------------------------------------- install

if (-not $Name) {
    $default = ($env:COMPUTERNAME).ToLower() -replace '[^a-z0-9-]', '-'
    if ($Yes) { $Name = $default }
    else {
        $Name = Read-Host "name for this machine [$default]"
        if (-not $Name) { $Name = $default }
    }
}

Write-Host ""
Write-Host "  install to   $Binary"
Write-Host "  state in     $StateDir"
if ($Scope -eq 'system') {
    Write-Host "  service      scheduled task at boot, as SYSTEM"
    Write-Host "  reachable    always, including before anyone logs in"
} else {
    Write-Host "  service      scheduled task at logon, as $env:USERNAME"
    Write-Host "  reachable    only while you are logged in"
}
Write-Host "  proxy        $Proxies"
Write-Host "  name         $Name"
Write-Host ""

if (-not $Yes) {
    $c = Read-Host 'proceed? [Y/n]'
    if ($c -match '^[nN]') { Write-Host 'cancelled'; exit 0 }
}

if (-not $Password) { $Password = $env:MULTISSH_PASSWORD }
if (-not $Password) {
    $sec = Read-Host 'enrollment password' -AsSecureString
    $Password = [Runtime.InteropServices.Marshal]::PtrToStringAuto(
        [Runtime.InteropServices.Marshal]::SecureStringToBSTR($sec))
}
if (-not $Password) { Die 'a password is required' }

New-Item -ItemType Directory -Force -Path $StateDir | Out-Null
if ($Scope -eq 'system') {
    # Keys and certificate are readable only by SYSTEM and Administrators.
    icacls $StateDir /inheritance:r /grant 'SYSTEM:(OI)(CI)F' /grant 'Administrators:(OI)(CI)F' | Out-Null
}
# A user install lives under LOCALAPPDATA, which is already private to you --
# and a local administrator could read it either way, exactly as on Linux.

Download-Binary

# The agent generates its own keys, so no ssh-keygen is needed -- a stock
# Windows install may not have one. Private halves never leave the machine.
$idPath   = Join-Path $StateDir 'agent_identity'
$hostPath = Join-Path $StateDir 'agent_host_key'
$keys = & $Binary -show-keys -identity $idPath -host-key $hostPath
if ($LASTEXITCODE -ne 0) { Die "the agent could not generate its keys" }

$identityKey = ($keys | Where-Object { $_ -like 'identity *' } | Select-Object -First 1) -replace '^identity ', ''
$hostKey     = ($keys | Where-Object { $_ -like 'host *' }     | Select-Object -First 1) -replace '^host ', ''
if (-not $identityKey -or -not $hostKey) {
    Die "unexpected output from -show-keys; got: $keys"
}

Write-Host 'enrolling...'
$body = @{
    password     = $Password
    name         = $Name
    identity_key = $identityKey
    host_key     = $hostKey
    version      = $Version
    platform     = 'windows-amd64'
} | ConvertTo-Json

try {
    $resp = Invoke-RestMethod -Uri "$BaseUrl/enroll" -Method Post -Body $body `
        -ContentType 'application/json' -UseBasicParsing
} catch {
    Die "enrolment refused (wrong or expired password?): $($_.Exception.Message)"
}

Write-KeyFile (Join-Path $StateDir 'agent_identity-cert.pub') $resp.certificate
Write-KeyFile (Join-Path $StateDir 'proxy_ca.pub')            $resp.ca
Write-KeyFile (Join-Path $StateDir 'agent_authorized_keys')   $resp.authorized_keys

$argline = "-proxy $Proxies -identity `"$idPath`" -host-key `"$hostPath`" " +
           "-identity-cert `"$(Join-Path $StateDir 'agent_identity-cert.pub')`" " +
           "-ca `"$(Join-Path $StateDir 'proxy_ca.pub')`" " +
           "-authorized-keys `"$(Join-Path $StateDir 'agent_authorized_keys')`""

@{
    version   = $Version
    binary    = $Binary
    state     = $StateDir
    scope     = $Scope
    platform  = 'windows-amd64'
    proxy     = $Proxies
    ca        = $CaKey
    canonical = $resp.canonical
    args      = $argline
    installed = (Get-Date).ToUniversalTime().ToString('o')
} | ConvertTo-Json | Set-Content $Manifest

# Keep a copy so update and uninstall work when the proxy is gone.
try { Invoke-WebRequest -Uri "$BaseUrl/install.ps1" -OutFile (Join-Path $StateDir 'manage.ps1') -UseBasicParsing } catch {}

Start-Agent $argline

Write-Host ""
Write-Host "  installed and running"
Write-Host ""
Write-Host "  canonical  $($resp.canonical)   always works"
Write-Host "  friendly   $($resp.friendly)   yours unless another machine already holds it"
Write-Host ""
Write-Host "  ssh -J <proxy> anything@$($resp.friendly)"
if ($Scope -eq 'system') {
    Write-Host "  (the username is ignored; the shell runs as SYSTEM, so per-user"
    Write-Host "   tools such as winget are not on its PATH)"
} else {
    Write-Host "  (the username is ignored; the shell runs as $env:USERNAME)"
}
Write-Host ""
Write-Host "  update, roll back or remove:"
Write-Host "    `$m = '$StateDir\manage.ps1'"
Write-Host "    & ([scriptblock]::Create((Get-Content `$m -Raw))) -Update"
Write-Host "    & ([scriptblock]::Create((Get-Content `$m -Raw))) -Rollback"
Write-Host "    & ([scriptblock]::Create((Get-Content `$m -Raw))) -Uninstall"
Write-Host ""
