# multiSSH agent installer for Windows.
#
# Generated by the proxy, which bakes in its own certificate authority and
# address below, so the agent pins the right authority from its first connect.
#
# Registered as a scheduled task at boot rather than a service: a proper
# Windows service needs a service-control handler in the binary, and this path
# has not been exercised on real hardware yet. Restart-on-failure is weaker as
# a result; the agent's own reconnect loop covers the common case.
#
#   irm https://proxy/install.ps1 | iex
#   & ([scriptblock]::Create((irm https://proxy/install.ps1))) -Uninstall

[CmdletBinding()]
param(
    [switch]$Uninstall,
    [switch]$Update,
    [switch]$Rollback,
    [switch]$Reenroll,
    [switch]$Yes,
    [string]$Name,
    [string]$Password
)

$ErrorActionPreference = 'Stop'

$BaseUrl  = '__BASE_URL__'
$Proxies  = '__PROXIES__'
$CaKey    = '__CA__'
$Version  = '__VERSION__'
$Hashes   = '__HASHES__'

$InstallDir = Join-Path $env:ProgramFiles 'multiSSH'
$StateDir   = Join-Path $env:ProgramData 'multiSSH'
$Binary     = Join-Path $InstallDir 'multissh-agent.exe'
$Manifest   = Join-Path $StateDir 'manifest.json'
$TaskName   = 'multiSSH agent'

function Die($m) { Write-Error $m; exit 1 }

function Assert-Admin {
    $id = [Security.Principal.WindowsIdentity]::GetCurrent()
    $p  = New-Object Security.Principal.WindowsPrincipal($id)
    if (-not $p.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {
        Die 'run this from an elevated PowerShell (Run as Administrator)'
    }
}

function Get-Manifest {
    if (Test-Path $Manifest) { return Get-Content $Manifest -Raw | ConvertFrom-Json }
    return $null
}

function Stop-Agent {
    schtasks /End /TN $TaskName 2>$null | Out-Null
}

function Start-Agent($argline) {
    schtasks /Delete /TN $TaskName /F 2>$null | Out-Null
    # Runs as SYSTEM at boot, so the machine is reachable before anyone logs in.
    schtasks /Create /TN $TaskName /RU SYSTEM /SC ONSTART /RL HIGHEST /F `
        /TR "`"$Binary`" $argline" | Out-Null
    schtasks /Run /TN $TaskName | Out-Null
}

Assert-Admin

# ------------------------------------------------------------- uninstall

if ($Uninstall) {
    $m = Get-Manifest
    if (-not $m) { Die "nothing installed here (no $Manifest)" }
    Write-Host "will remove:"
    Write-Host "  $($m.binary)"
    Write-Host "  $($m.state)  (identity key, host key, certificate)"
    Write-Host "  scheduled task '$TaskName'"
    if (-not $Yes) {
        $c = Read-Host 'remove, including the keys? [y/N]'
        if ($c -notmatch '^[yY]') { Write-Host 'cancelled'; exit 0 }
    }
    # Ordered so that an uninstall driven over the agent's own tunnel finishes:
    # ending the task kills this script with it, so everything that can be done
    # while the agent still runs is done first. Windows refuses to delete a
    # running .exe but allows it to be renamed, so the binary is moved aside
    # and only then deleted.
    schtasks /Delete /TN $TaskName /F 2>$null | Out-Null
    Remove-Item -Recurse -Force $m.state -ErrorAction SilentlyContinue
    if (Test-Path $m.binary) {
        Move-Item -Force $m.binary "$($m.binary).removing" -ErrorAction SilentlyContinue
    }
    Remove-Item -Force "$($m.binary).prev", "$($m.binary).new" -ErrorAction SilentlyContinue
    Write-Host 'removed.'
    Stop-Agent
    Remove-Item -Recurse -Force $InstallDir -ErrorAction SilentlyContinue
    exit 0
}

# ------------------------------------------------------------- rollback

if ($Rollback) {
    $m = Get-Manifest
    if (-not $m) { Die "nothing installed here (no $Manifest)" }
    if (-not (Test-Path "$Binary.prev")) { Die "no previous binary saved at $Binary.prev" }
    Copy-Item -Force "$Binary.prev" "$Binary.rollback"
    Move-Item -Force "$Binary.rollback" $Binary
    # The recorded version no longer describes what is on disk, so clear it or
    # the next -Update would decide there was nothing to do.
    $m.version = 'rolled-back'
    $m | ConvertTo-Json | Set-Content $Manifest
    Restart-Agent $m.args
    Write-Host 'rolled back to the previous binary; run -Update to go forward again'
    exit 0
}

# ------------------------------------------------------------- download

function Expected-Hash {
    foreach ($pair in $Hashes -split ' ') {
        $p, $h = $pair -split ':', 2
        if ($p -eq 'windows-amd64') { return $h }
    }
    return $null
}

# Replaces the agent without stopping it first, matching install.sh.
#
# Windows will not let a running .exe be overwritten, but it will let one be
# renamed. So the outgoing binary is renamed aside and the new one takes its
# place; the running process is undisturbed and only the restart at the end
# interrupts anything. An update driven over the agent's own tunnel therefore
# cannot leave the machine with no agent at all.
function Download-Binary {
    $want = Expected-Hash
    if (-not $want) { Die 'the proxy has no agent build for windows-amd64' }
    New-Item -ItemType Directory -Force -Path $InstallDir | Out-Null
    $new = "$Binary.new"
    Write-Host "downloading agent $Version for windows-amd64"
    Invoke-WebRequest -Uri "$BaseUrl/dist/windows-amd64" -OutFile $new -UseBasicParsing
    $got = (Get-FileHash $new -Algorithm SHA256).Hash.ToLower()
    if ($got -ne $want.ToLower()) {
        Remove-Item $new -Force
        Die "checksum mismatch: expected $want, got $got"
    }
    if (Test-Path $Binary) {
        Remove-Item -Force "$Binary.prev" -ErrorAction SilentlyContinue
        Move-Item -Force $Binary "$Binary.prev"
    }
    Move-Item -Force $new $Binary
}

function Restart-Agent($argline) {
    schtasks /End /TN $TaskName 2>$null | Out-Null
    Start-Agent $argline
}

# ------------------------------------------------------------- update

# This copy has the proxy's version frozen into it from install time and the
# manifest holds that same value, so comparing them here would always report
# "already current". Fetch what the proxy is serving now and hand over to it.
if ($Update -and -not $env:MULTISSH_NO_REFETCH) {
    try {
        $fresh = Join-Path $StateDir 'install.fetched.ps1'
        Invoke-WebRequest -Uri "$BaseUrl/install.ps1" -OutFile $fresh -UseBasicParsing
        $env:MULTISSH_NO_REFETCH = '1'
        & $fresh -Update
        Remove-Item -Force $fresh -ErrorAction SilentlyContinue
        exit $LASTEXITCODE
    } catch {
        Write-Host "could not reach $BaseUrl; continuing with this copy"
    }
}

$existing = Get-Manifest
if ($existing -and -not $Reenroll -and -not $Uninstall) {
    if (-not $Update) {
        Write-Host "already installed here ($($existing.canonical)); updating instead."
        Write-Host "pass -Reenroll to discard that identity and enrol afresh."
    }
    if ($existing.ca -ne $CaKey) { Die 'this proxy has a different authority than the one enrolled with; refusing' }
    if ($existing.version -eq $Version) { Write-Host "already current ($Version)"; exit 0 }
    Download-Binary
    $existing.version = $Version
    $existing | ConvertTo-Json | Set-Content $Manifest
    Restart-Agent $existing.args
    Write-Host "updated to $Version; keys and certificate untouched"
    exit 0
}

# ------------------------------------------------------------- install

if (-not $Name) {
    $default = ($env:COMPUTERNAME).ToLower() -replace '[^a-z0-9-]', '-'
    if ($Yes) { $Name = $default }
    else {
        $Name = Read-Host "name for this machine [$default]"
        if (-not $Name) { $Name = $default }
    }
}

Write-Host ""
Write-Host "  install to   $Binary"
Write-Host "  state in     $StateDir"
Write-Host "  service      scheduled task at boot, as SYSTEM"
Write-Host "  proxy        $Proxies"
Write-Host "  name         $Name"
Write-Host ""

if (-not $Yes) {
    $c = Read-Host 'proceed? [Y/n]'
    if ($c -match '^[nN]') { Write-Host 'cancelled'; exit 0 }
}

if (-not $Password) { $Password = $env:MULTISSH_PASSWORD }
if (-not $Password) {
    $sec = Read-Host 'enrollment password' -AsSecureString
    $Password = [Runtime.InteropServices.Marshal]::PtrToStringAuto(
        [Runtime.InteropServices.Marshal]::SecureStringToBSTR($sec))
}
if (-not $Password) { Die 'a password is required' }

New-Item -ItemType Directory -Force -Path $StateDir | Out-Null
# Keys and certificate are readable only by SYSTEM and Administrators.
icacls $StateDir /inheritance:r /grant 'SYSTEM:(OI)(CI)F' /grant 'Administrators:(OI)(CI)F' | Out-Null

Download-Binary

# The agent generates its own keys, so no ssh-keygen is needed -- a stock
# Windows install may not have one. Private halves never leave the machine.
$idPath   = Join-Path $StateDir 'agent_identity'
$hostPath = Join-Path $StateDir 'agent_host_key'
$keys = & $Binary -show-keys -identity $idPath -host-key $hostPath
$identityKey = ($keys | Select-String '^identity ').ToString() -replace '^identity ', ''
$hostKey     = ($keys | Select-String '^host ').ToString()     -replace '^host ', ''

Write-Host 'enrolling...'
$body = @{
    password     = $Password
    name         = $Name
    identity_key = $identityKey
    host_key     = $hostKey
    version      = $Version
    platform     = 'windows-amd64'
} | ConvertTo-Json

try {
    $resp = Invoke-RestMethod -Uri "$BaseUrl/enroll" -Method Post -Body $body `
        -ContentType 'application/json' -UseBasicParsing
} catch {
    Die 'enrolment refused (wrong or expired password?)'
}

Set-Content -Path (Join-Path $StateDir 'agent_identity-cert.pub') -Value $resp.certificate -NoNewline
Set-Content -Path (Join-Path $StateDir 'proxy_ca.pub')            -Value $resp.ca -NoNewline
Set-Content -Path (Join-Path $StateDir 'agent_authorized_keys')   -Value $resp.authorized_keys -NoNewline

$argline = "-proxy $Proxies -identity `"$idPath`" -host-key `"$hostPath`" " +
           "-identity-cert `"$(Join-Path $StateDir 'agent_identity-cert.pub')`" " +
           "-ca `"$(Join-Path $StateDir 'proxy_ca.pub')`" " +
           "-authorized-keys `"$(Join-Path $StateDir 'agent_authorized_keys')`""

@{
    version   = $Version
    binary    = $Binary
    state     = $StateDir
    scope     = 'system'
    platform  = 'windows-amd64'
    proxy     = $Proxies
    ca        = $CaKey
    canonical = $resp.canonical
    args      = $argline
    installed = (Get-Date).ToUniversalTime().ToString('o')
} | ConvertTo-Json | Set-Content $Manifest

# Keep a copy so update and uninstall work when the proxy is gone.
try { Invoke-WebRequest -Uri "$BaseUrl/install.ps1" -OutFile (Join-Path $StateDir 'manage.ps1') -UseBasicParsing } catch {}

Start-Agent $argline

Write-Host ""
Write-Host "  installed and running"
Write-Host ""
Write-Host "  canonical  $($resp.canonical)   always works"
Write-Host "  friendly   $($resp.friendly)   yours unless another machine already holds it"
Write-Host ""
Write-Host "  ssh -J <proxy> Administrator@$($resp.friendly)"
Write-Host ""
Write-Host "  update or remove:"
Write-Host "    & ([scriptblock]::Create((Get-Content '$StateDir\manage.ps1' -Raw))) -Update"
Write-Host "    & ([scriptblock]::Create((Get-Content '$StateDir\manage.ps1' -Raw))) -Rollback"
Write-Host "    & ([scriptblock]::Create((Get-Content '$StateDir\manage.ps1' -Raw))) -Uninstall"
Write-Host ""
