#!/bin/sh
# multiSSH agent installer.
#
# Generated by the proxy, which bakes in its own certificate authority and
# address below. That is deliberate: the agent pins the right authority from
# its first connect, anchored on the TLS certificate you fetched this over,
# so there is no trust-on-first-use window for the agent-to-proxy hop.
#
# A copy of this script and a manifest of what it installed are saved next to
# the agent, so update and uninstall keep working when the proxy is gone.
set -eu

BASE_URL='__BASE_URL__'
PROXIES='__PROXIES__'
CA_KEY='__CA__'
VERSION='__VERSION__'
HASHES='__HASHES__'

MODE=install
REENROLL=
ASSUME_YES=${MULTISSH_YES:-}

for arg in "$@"; do
    case "$arg" in
        --uninstall) MODE=uninstall ;;
        --update)    MODE=update ;;
        --rollback)  MODE=rollback ;;
        -y|--yes)    ASSUME_YES=1 ;;
        --reenroll)  REENROLL=1 ;;
        -h|--help)
            cat <<EOF
multiSSH agent installer

  sh install.sh              install and enrol this machine
  sh install.sh --update     replace the binary, keep keys and certificate
  sh install.sh --rollback   go back to the previous binary
  sh install.sh --uninstall  stop and remove everything

  -y, --yes                  accept defaults, do not prompt
      --reenroll             force a fresh enrolment over an existing install

Piped from curl, pass options after '--':
  curl -fsSL $BASE_URL/install.sh | sudo sh -s -- --uninstall

Non-interactive installs read: MULTISSH_PASSWORD (required), MULTISSH_NAME,
MULTISSH_PROXY, MULTISSH_PREFIX, MULTISSH_STATE_DIR, MULTISSH_SCOPE.
EOF
            exit 0 ;;
        *) echo "unknown option: $arg (try --help)" >&2; exit 2 ;;
    esac
done

# Where this copy of the script is. The copy saved beside the agent lives in
# the state directory, so it can find its own manifest even when the install
# used paths that a freshly fetched script could never guess.
#
# Only when we were actually run from a file. Piped from curl, $0 is the shell
# name with no slash and there is no script directory -- dirname would then
# yield ".", making SELF_DIR the current directory. Adopting a manifest from
# there is a local privilege escalation: any user can drop a manifest in a
# world-writable directory an admin happens to `cd` into before piping the
# installer to sudo, and its M_STATE/M_BIN would be sourced as root (and
# --uninstall would rm -rf that M_STATE). So: a path with no slash means no
# saved copy, and SELF_DIR stays empty.
case "$0" in
    */*) SELF_DIR=$(CDPATH='' cd -- "$(dirname -- "$0")" 2>/dev/null && pwd) || SELF_DIR= ;;
    *)   SELF_DIR= ;;
esac

die() { echo "error: $*" >&2; exit 1; }
have() { command -v "$1" >/dev/null 2>&1; }

# stdin is the script itself when piped from curl, so prompts must read the
# terminal directly. When there is no terminal at all, run unattended rather
# than hang on a question nobody can answer.
INTERACTIVE=1
[ -r /dev/tty ] && [ -z "$ASSUME_YES" ] || INTERACTIVE=
ask() { # ask VAR "prompt" "default"
    _d=$3
    if [ -n "$INTERACTIVE" ]; then
        printf '%s [%s]: ' "$2" "$_d" > /dev/tty
        read -r _a < /dev/tty || _a=
        [ -n "$_a" ] || _a=$_d
    else
        _a=$_d
    fi
    eval "$1=\$_a"
}
ask_secret() { # ask_secret VAR "prompt"
    if [ -n "${MULTISSH_PASSWORD:-}" ]; then eval "$1=\$MULTISSH_PASSWORD"; return; fi
    [ -n "$INTERACTIVE" ] || die "no terminal; set MULTISSH_PASSWORD"
    printf '%s: ' "$2" > /dev/tty
    stty -echo < /dev/tty 2>/dev/null || true
    read -r _s < /dev/tty || _s=
    stty echo < /dev/tty 2>/dev/null || true
    printf '\n' > /dev/tty
    eval "$1=\$_s"
}

# ---------------------------------------------------------------- platform

case "$(uname -s)" in
    Linux)  OS=linux ;;
    Darwin) OS=darwin ;;
    *) die "unsupported system: $(uname -s)" ;;
esac
case "$(uname -m)" in
    x86_64|amd64)  ARCH=amd64 ;;
    aarch64|arm64) ARCH=arm64 ;;
    *) die "unsupported architecture: $(uname -m)" ;;
esac
PLATFORM="$OS-$ARCH"

# Scope follows reality: root installs system-wide, anyone else installs for
# themselves, because a system install would only fail later.
if [ "$(id -u)" = 0 ]; then SCOPE=${MULTISSH_SCOPE:-system}; else SCOPE=${MULTISSH_SCOPE:-user}; fi
if [ "$SCOPE" = system ] && [ "$(id -u)" != 0 ]; then
    die "a system install needs root; re-run with sudo, or let it default to a user install"
fi

if [ "$SCOPE" = system ]; then
    PREFIX=${MULTISSH_PREFIX:-/usr/local/bin}
    if [ "$OS" = darwin ]; then
        STATE=${MULTISSH_STATE_DIR:-/Library/Application Support/multissh-agent}
    else
        STATE=${MULTISSH_STATE_DIR:-/var/lib/multissh-agent}
    fi
else
    PREFIX=${MULTISSH_PREFIX:-$HOME/.local/bin}
    STATE=${MULTISSH_STATE_DIR:-$HOME/.config/multissh-agent}
fi

# A manifest next to this script beats any default. Without this, running the
# saved copy of a non-default install looks for a manifest in the default
# location, does not find one, and reports that nothing is installed.
if [ -z "${MULTISSH_STATE_DIR:-}" ] && [ -n "$SELF_DIR" ] && [ -f "$SELF_DIR/manifest" ]; then
    STATE=$SELF_DIR
fi

BIN="$PREFIX/multissh-agent"
MANIFEST="$STATE/manifest"

# launchd has two domains and they are not interchangeable. A LaunchDaemon in
# /Library runs as root at boot and needs root to install; a LaunchAgent in the
# user's own Library runs as them at login and needs nothing.
#
# These follow SCOPE, so they must be derived *after* SCOPE is final -- and the
# manifest below can change it. Computing them here and not again meant an
# uninstall that reads a system manifest while defaulting to user scope (a
# no-sudo run) would boot out the wrong domain and delete the wrong plist,
# leaving a root daemon running with its keys gone. So this is a function,
# called once SCOPE has settled.
set_launchd_paths() {
    PLIST=
    LAUNCH_DOMAIN=
    [ "$OS" = darwin ] || return 0
    if [ "$SCOPE" = system ]; then
        PLIST=/Library/LaunchDaemons/net.multissh.agent.plist
        LAUNCH_DOMAIN=system
    else
        PLIST="$HOME/Library/LaunchAgents/net.multissh.agent.plist"
        LAUNCH_DOMAIN="gui/$(id -u)"
    fi
}

# An existing manifest is authoritative about where this machine put things,
# which a freshly fetched script could not know if the paths were customised.
#
# Sourcing it runs its contents, so as root it must be root-owned. [ -O ] tests
# ownership by the effective user; as root that is true only for a root-owned
# file. This is a second line behind the SELF_DIR guard above: even a manifest
# reached by some other path must not hand an unprivileged writer control of
# what runs as root.
if [ -f "$MANIFEST" ]; then
    # -O (owned by the effective user) is outside the POSIX test spec but is
    # implemented by every shell this runs under -- dash, bash, busybox ash --
    # and is the exact question: as root, true only for a root-owned file.
    # shellcheck disable=SC3067
    if [ "$(id -u)" = 0 ] && [ ! -O "$MANIFEST" ]; then
        die "refusing to read $MANIFEST as root: it is not owned by root"
    fi
    # shellcheck disable=SC1090
    . "$MANIFEST"
    BIN=$M_BIN; STATE=$M_STATE; SCOPE=$M_SCOPE
    MANIFEST="$STATE/manifest"
fi

# SCOPE is now final -- the manifest, if any, has had its say.
set_launchd_paths

svc_name() { echo multissh-agent; }
svc_stop() {
    case "$OS-$SCOPE" in
        linux-system) systemctl stop "$(svc_name)" 2>/dev/null || true ;;
        linux-user)   systemctl --user stop "$(svc_name)" 2>/dev/null || true ;;
        darwin-*)     launchctl bootout "$LAUNCH_DOMAIN/net.multissh.agent" 2>/dev/null || true ;;
    esac
}
svc_start() {
    case "$OS-$SCOPE" in
        linux-system) systemctl daemon-reload; systemctl enable --now "$(svc_name)" ;;
        linux-user)
            systemctl --user daemon-reload; systemctl --user enable --now "$(svc_name)"
            # Without lingering the user manager is torn down at logout and not
            # started until the next login, so the agent is absent for exactly
            # the machine states a rescue tool exists for: nobody logged in.
            # Needs root, so it is a request rather than a step; if it is
            # refused the install is still good, just only while logged in.
            if command -v loginctl >/dev/null 2>&1 && [ "$(loginctl show-user "$(id -un)" -p Linger --value 2>/dev/null)" != yes ]; then
                if ! loginctl enable-linger "$(id -un)" 2>/dev/null; then
                    echo "note: this agent runs only while you are logged in."
                    echo "      to keep it running across logout and reboot:"
                    echo "        sudo loginctl enable-linger $(id -un)"
                fi
            fi
            ;;
        darwin-*)
            mkdir -p "$(dirname "$PLIST")"
            launchctl bootstrap "$LAUNCH_DOMAIN" "$PLIST" 2>/dev/null || launchctl load "$PLIST"
            ;;
    esac
}
# svc_restart is the last thing an update does, and it may well kill this
# script: when the update was started over the agent's own tunnel, this shell
# is inside the unit's cgroup. That is fine here and only here, because by this
# point the new binary is already in place and the manifest already written.
# Nothing after this line may matter.
svc_restart() {
    case "$OS-$SCOPE" in
        linux-system) systemctl restart "$(svc_name)" ;;
        linux-user)   systemctl --user restart "$(svc_name)" ;;
        darwin-*)     launchctl kickstart -k "$LAUNCH_DOMAIN/net.multissh.agent" ;;
    esac
}

# set_manifest_version rewrites just the version line, leaving the paths and
# identity the manifest records untouched.
set_manifest_version() {
    _v=$1
    sed "s|^M_VERSION=.*|M_VERSION='$_v'|" "$MANIFEST" > "$MANIFEST.tmp" &&
        mv "$MANIFEST.tmp" "$MANIFEST"
}

# ---------------------------------------------------------------- uninstall

if [ "$MODE" = uninstall ]; then
    [ -f "$MANIFEST" ] || die "nothing installed here (no $MANIFEST)"
    echo "will remove:"
    echo "  $BIN"
    echo "  $STATE  (identity key, host key, certificate)"
    echo "  the service unit"
    if [ -n "$INTERACTIVE" ]; then
        printf 'remove, including the keys? [y/N]: ' > /dev/tty
        read -r c < /dev/tty || c=
        case "$c" in y|Y|yes) ;; *) echo "cancelled"; exit 0 ;; esac
    fi
    # Everything is removed before anything is stopped, for the same reason
    # updates swap the binary before restarting: an uninstall run over the
    # agent's own tunnel is killed the instant the service goes down. Doing the
    # removal first means that kill lands after the work is finished rather
    # than halfway through it. Unlinking files that are open or running is
    # fine on Unix -- this script included.
    rm -f "$BIN" "$BIN.prev" "$BIN.new"
    rm -rf "$STATE"
    case "$OS-$SCOPE" in
        linux-system) rm -f /etc/systemd/system/multissh-agent.service ;;
        linux-user)   rm -f "$HOME/.config/systemd/user/multissh-agent.service" ;;
        darwin-*)     rm -f "$PLIST" ;;
    esac
    echo "removed."
    svc_stop
    case "$OS-$SCOPE" in
        linux-system) systemctl daemon-reload 2>/dev/null || true ;;
        linux-user)   systemctl --user daemon-reload 2>/dev/null || true ;;
    esac
    exit 0
fi

# Re-running the installer on a machine that already has one should update it,
# not enrol it a second time under a new identity. Enrolling again would leave
# the old certificate valid and the old name occupied.
if [ "$MODE" = install ] && [ -f "$MANIFEST" ] && [ -z "$REENROLL" ]; then
    echo "already installed here (${M_CANONICAL:-unknown}); updating instead."
    echo "pass --reenroll to discard that identity and enrol afresh."
    MODE=update
fi

# ---------------------------------------------------------------- download

fetch() { # fetch URL DEST
    if have curl; then curl -fsSL "$1" -o "$2"
    elif have wget; then wget -qO "$2" "$1"
    else die "need curl or wget"; fi
}

# Must always exit zero. Under 'set -e' a non-zero status here aborts the whole
# script, and a loop that ends on a non-matching entry would do exactly that --
# which stayed hidden while only one build existed and the match came last.
expected_hash() {
    for _pair in $HASHES; do
        case "$_pair" in
            "$PLATFORM":*) echo "${_pair#*:}"; return 0 ;;
        esac
    done
    return 0
}

# sha256_of prints the hash, or nothing if no hasher is installed. The caller
# must treat the empty case as a failure, not as a pass: an absent hasher is
# exactly when an unverified binary would slip through.
sha256_of() {
    if have sha256sum; then sha256sum "$1" | cut -d' ' -f1
    elif have shasum; then shasum -a 256 "$1" | cut -d' ' -f1
    else echo ""; fi
}

# download_binary replaces the agent without ever stopping it first.
#
# This ordering is the whole safety property. It used to stop the service, then
# move the new binary into place -- and when an update is driven over the
# agent's own tunnel, which is the only way to reach a machine behind NAT, that
# stop kills the update script too: systemd tears down the whole cgroup the
# script is running in. The binary was then never replaced, the unit stayed
# stopped, and systemd would not restart it because it had been stopped
# deliberately. The machine was unreachable, permanently, from one update.
#
# The stop was only there because a running executable cannot be overwritten in
# place -- ETXTBSY. But rename(2) has no such restriction: the running process
# keeps its own inode, and the new file simply takes the name. So download and
# verify first, swap atomically, and leave restarting to the very last step,
# by which point everything is already committed. If the script dies before
# that, the old agent is still running and the next restart picks up the new
# binary. There is no window in which the machine is left with neither.
#
# The temporary file must sit beside the target, or mv falls back to copy and
# unlink across filesystems and ETXTBSY returns.
download_binary() {
    WANT=$(expected_hash)
    [ -n "$WANT" ] || die "the proxy has no agent build for $PLATFORM"
    mkdir -p "$PREFIX"
    NEW="$BIN.new"
    echo "downloading agent $VERSION for $PLATFORM"
    fetch "$BASE_URL/dist/$PLATFORM" "$NEW" || { rm -f "$NEW"; die "download failed"; }
    GOT=$(sha256_of "$NEW")
    # Fail closed. An empty GOT means no hasher is installed, so the binary is
    # unverified -- which must stop the install, not pass it. This was the one
    # place the two installers disagreed: install.ps1 always verifies, and a
    # POSIX box without sha256sum or shasum silently did not.
    if [ -z "$GOT" ]; then
        rm -f "$NEW"; die "cannot verify the download: install sha256sum or shasum first"
    fi
    if [ "$GOT" != "$WANT" ]; then
        rm -f "$NEW"; die "checksum mismatch: expected $WANT, got $GOT"
    fi
    chmod 0755 "$NEW"
    # Keep the outgoing binary so --rollback has something to go back to.
    if [ -f "$BIN" ]; then
        cp -p "$BIN" "$BIN.prev.tmp" && mv "$BIN.prev.tmp" "$BIN.prev"
    fi
    mv "$NEW" "$BIN"
}

# ---------------------------------------------------------------- update

if [ "$MODE" = rollback ]; then
    [ -f "$MANIFEST" ] || die "nothing installed here (no $MANIFEST)"
    [ -f "$BIN.prev" ] || die "no previous binary saved at $BIN.prev"
    cp -p "$BIN.prev" "$BIN.rollback.tmp"
    mv "$BIN.rollback.tmp" "$BIN"
    # The recorded version no longer describes what is on disk. Clearing it
    # means the next --update will re-apply rather than decide there is
    # nothing to do.
    set_manifest_version "rolled-back"
    svc_restart
    echo "rolled back to the previous binary; run --update to go forward again"
    exit 0
fi

# The saved copy of this script has the proxy's version frozen into it from
# install time, and the manifest records that same value -- so comparing the
# two here would always say "already current" and the agent could never be
# updated by the very command documented for updating it. Ask the proxy for
# the script it is serving now and hand over to that.
#
# The proxy has to be reachable to download a binary from in any case, so this
# costs nothing that was not already required.
if [ "$MODE" = update ] && [ -z "${MULTISSH_NO_REFETCH:-}" ]; then
    [ -f "$MANIFEST" ] || die "nothing installed here (no $MANIFEST)"
    FRESH="$STATE/install.fetched.sh"
    if fetch "$BASE_URL/install.sh" "$FRESH"; then
        MULTISSH_NO_REFETCH=1
        MULTISSH_STATE_DIR=$STATE
        MULTISSH_PREFIX=$(dirname "$BIN")
        export MULTISSH_NO_REFETCH MULTISSH_STATE_DIR MULTISSH_PREFIX
        sh "$FRESH" --update ${ASSUME_YES:+-y}
        rc=$?
        rm -f "$FRESH"
        exit $rc
    fi
    rm -f "$FRESH"
    echo "could not reach $BASE_URL; continuing with this copy" >&2
fi

if [ "$MODE" = update ]; then
    [ -f "$MANIFEST" ] || die "nothing installed here (no $MANIFEST)"
    [ "$M_CA" = "$CA_KEY" ] || die "this proxy has a different authority than the one enrolled with; refusing"
    if [ "$M_VERSION" = "$VERSION" ]; then echo "already current ($VERSION)"; exit 0; fi
    download_binary
    set_manifest_version "$VERSION"
    svc_restart
    echo "updated to $VERSION; keys and certificate untouched"
    exit 0
fi

# ---------------------------------------------------------------- install

DEFAULT_NAME=$(hostname 2>/dev/null || echo machine)
DEFAULT_NAME=$(echo "$DEFAULT_NAME" | tr '[:upper:]' '[:lower:]' | sed 's/\..*//; s/[^a-z0-9-]/-/g')
ask NAME "name for this machine" "${MULTISSH_NAME:-$DEFAULT_NAME}"
PROXY_LIST=${MULTISSH_PROXY:-$PROXIES}

cat <<EOF

  install to   $BIN
  state in     $STATE
  scope        $SCOPE
  proxy        $PROXY_LIST
  name         $NAME

EOF

if [ -n "$INTERACTIVE" ]; then
    printf 'proceed? [Y/n/c=customise]: ' > /dev/tty
    read -r c < /dev/tty || c=
    case "$c" in
        n|N) echo "cancelled"; exit 0 ;;
        c|C)
            ask PREFIX "install directory" "$PREFIX"
            ask STATE  "state directory"   "$STATE"
            ask PROXY_LIST "proxy url(s), comma separated" "$PROXY_LIST"
            BIN="$PREFIX/multissh-agent"; MANIFEST="$STATE/manifest" ;;
    esac
fi

ask_secret PASSWORD "enrollment password"
[ -n "$PASSWORD" ] || die "a password is required"

mkdir -p "$STATE"
chmod 0700 "$STATE"
download_binary

# Private keys are generated here and never leave the machine; only the public
# halves are sent for signing.
have ssh-keygen || die "need ssh-keygen"
[ -f "$STATE/agent_identity" ]  || ssh-keygen -t ed25519 -N '' -q -C "multissh-identity" -f "$STATE/agent_identity"
[ -f "$STATE/agent_host_key" ]  || ssh-keygen -t ed25519 -N '' -q -C "multissh-host"     -f "$STATE/agent_host_key"

json_escape() { printf '%s' "$1" | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g' | tr -d '\n'; }
REQ=$(printf '{"password":"%s","name":"%s","identity_key":"%s","host_key":"%s","version":"%s","platform":"%s"}' \
    "$(json_escape "$PASSWORD")" "$(json_escape "$NAME")" \
    "$(json_escape "$(cat "$STATE/agent_identity.pub")")" \
    "$(json_escape "$(cat "$STATE/agent_host_key.pub")")" \
    "$VERSION" "$PLATFORM")

echo "enrolling..."
RESP=$(printf '%s' "$REQ" | curl -fsSL -X POST -H 'Content-Type: application/json' --data-binary @- "$BASE_URL/enroll") \
    || die "enrolment refused (wrong or expired password?)"

field() { printf '%s' "$RESP" | sed -n "s/.*\"$1\":\"\\([^\"]*\\)\".*/\\1/p" | head -1; }
unescape() { printf '%b' "$1"; }

unescape "$(field certificate)"      > "$STATE/agent_identity-cert.pub"
unescape "$(field ca)"               > "$STATE/proxy_ca.pub"
unescape "$(field authorized_keys)"  > "$STATE/agent_authorized_keys"
CANONICAL=$(field canonical)
FRIENDLY=$(field friendly)
[ -s "$STATE/agent_identity-cert.pub" ] || die "the proxy returned no certificate"

printf 'PROXY=%s\n' "$PROXY_LIST" > "$STATE/config"
chmod 0600 "$STATE"/agent_identity "$STATE"/agent_host_key "$STATE/config"

# ---------------------------------------------------------------- service

# The agent's arguments, one per line, so that a path containing a space stays
# one argument. macOS puts a system install's state in
#   /Library/Application Support/multissh-agent
# and the previous single string was word-split when the plist was built, which
# turned that into two arguments and handed the agent a path that does not
# exist. Nothing on Linux has a space by default, which is why it never showed.
agent_args() {
    printf '%s\n' \
        -proxy "$PROXY_LIST" \
        -identity "$STATE/agent_identity" \
        -host-key "$STATE/agent_host_key" \
        -identity-cert "$STATE/agent_identity-cert.pub" \
        -ca "$STATE/proxy_ca.pub" \
        -authorized-keys "$STATE/agent_authorized_keys"
}

# systemd accepts quoted arguments, so quote every one rather than hoping none
# of them needs it.
ARGS=$(agent_args | sed 's/.*/"&"/' | tr '\n' ' ')

case "$OS-$SCOPE" in
    linux-*)
        if [ "$SCOPE" = system ]; then UNIT=/etc/systemd/system/multissh-agent.service
        else UNIT="$HOME/.config/systemd/user/multissh-agent.service"; mkdir -p "$(dirname "$UNIT")"; fi
        cat > "$UNIT" <<EOF
[Unit]
Description=multiSSH agent
After=network-online.target
Wants=network-online.target

[Service]
ExecStart=$BIN $ARGS
Restart=always
RestartSec=5
LimitNOFILE=65535
WorkingDirectory=$STATE

[Install]
WantedBy=$( [ "$SCOPE" = system ] && echo multi-user.target || echo default.target )
EOF
        ;;
    darwin-*)
        # PLIST is chosen by scope far above. Do not set it here: an earlier
        # version reassigned it to the LaunchDaemon path at this point, which
        # undid the scope split silently -- a user install enrolled, then died
        # writing to /Library/LaunchDaemons.
        mkdir -p "$(dirname "$PLIST")"
        # & and < are legal in a path and would produce a plist launchd
        # refuses to parse, which it reports as the job simply not existing.
        xml_escape() { sed -e 's/&/\&amp;/g' -e 's/</\&lt;/g' -e 's/>/\&gt;/g'; }
        {
            cat <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0"><dict>
  <key>Label</key><string>net.multissh.agent</string>
  <key>ProgramArguments</key><array>
EOF
            printf '%s\n' "$BIN" | xml_escape | sed 's|.*|    <string>&</string>|'
            agent_args      | xml_escape | sed 's|.*|    <string>&</string>|'
            cat <<EOF
  </array>
  <key>RunAtLoad</key><true/>
  <key>KeepAlive</key><true/>
  <key>StandardOutPath</key><string>$(printf '%s' "$STATE/agent.log" | xml_escape)</string>
  <key>StandardErrorPath</key><string>$(printf '%s' "$STATE/agent.log" | xml_escape)</string>
</dict></plist>
EOF
        } > "$PLIST"
        ;;
esac

cat > "$MANIFEST" <<EOF
# multiSSH agent install manifest -- read by --update and --uninstall
M_VERSION='$VERSION'
M_BIN='$BIN'
M_STATE='$STATE'
M_SCOPE='$SCOPE'
M_PLATFORM='$PLATFORM'
M_PROXY='$PROXY_LIST'
M_CA='$CA_KEY'
M_CANONICAL='$CANONICAL'
M_INSTALLED='$(date -u +%Y-%m-%dT%H:%M:%SZ)'
EOF
chmod 0600 "$MANIFEST"

# Keep a copy so update and uninstall work with the proxy gone.
if [ -n "${SCRIPT_SELF:-}" ] && [ -f "$SCRIPT_SELF" ]; then
    cp "$SCRIPT_SELF" "$STATE/manage.sh"
else
    fetch "$BASE_URL/install.sh" "$STATE/manage.sh" || true
fi
chmod 0700 "$STATE/manage.sh" 2>/dev/null || true

svc_start

cat <<EOF

  installed and running

  canonical  $CANONICAL      always works
  friendly   $(printf "%-22s" "$FRIENDLY") yours unless another machine already holds it

  ssh -J <proxy> root@$FRIENDLY

  update, roll back or remove:
    sh $STATE/manage.sh --update
    sh $STATE/manage.sh --rollback
    sh $STATE/manage.sh --uninstall

  These are safe to run over the tunnel itself: the binary is swapped before
  anything is restarted, so an interrupted update leaves the old agent running
  rather than no agent at all.

EOF
