# multiSSH agent installer for Windows.
#
# Generated by the proxy, which bakes in its own certificate authority and
# address below, so the agent pins the right authority from its first connect.
#
# Registered as a scheduled task at boot rather than a service: a proper
# Windows service needs a service-control handler in the binary. The task is
# set to restart on failure and to have no execution time limit, so the gap
# between this and a service is smaller than it looks.
#
# Recommended, because it survives an error without closing your window and
# needs no execution-policy change:
#
#   irm https://proxy/install.ps1 -OutFile $env:TEMP\multissh-install.ps1
#   powershell -ExecutionPolicy Bypass -File $env:TEMP\multissh-install.ps1
#
# Elevated installs run as SYSTEM from a boot trigger; unelevated ones run as
# you from a logon trigger. -Scope system|user forces either. Both can be
# installed side by side.
#
# Options need the file form, or the scriptblock form -- piping into iex gives
# no way to pass arguments:
#
#   & ([scriptblock]::Create((irm https://proxy/install.ps1))) -Uninstall

[CmdletBinding()]
param(
    [switch]$Uninstall,
    [switch]$Update,
    [switch]$Rollback,
    [switch]$StartOnly,
    [switch]$Reenroll,
    [switch]$Yes,
    [string]$Name,
    [string]$Password,
    [ValidateSet('system', 'user')]
    [string]$Scope
)

$ErrorActionPreference = 'Stop'

# Invoke-WebRequest draws a progress bar by default, and over a pseudo-terminal
# that becomes thousands of lines of redrawn counters -- which is what an update
# driven over the tunnel actually sees, burying whatever it needed to say. It
# also makes the download dramatically slower.
$ProgressPreference = 'SilentlyContinue'

$BaseUrl  = '__BASE_URL__'
$Proxies  = '__PROXIES__'
$CaKey    = '__CA__'
$Version  = '__VERSION__'
$Hashes   = '__HASHES__'

# Two scopes, as on Linux.
#
#   system  runs as SYSTEM from a boot trigger, so the machine is reachable
#           before anyone logs in. Needs an elevated shell.
#   user    runs as you from a logon trigger, with your profile, your PATH and
#           your per-user applications -- winget among them. Needs no
#           administrator, and is not reachable while you are logged out.
#
# Both can be installed at once, and usefully so: the SYSTEM one is the rescue
# path, the user one is the comfortable one. They keep separate directories,
# separate keys and separate scheduled tasks, so neither can disturb the other.
$SystemInstallDir = Join-Path $env:ProgramFiles 'multiSSH'
$SystemStateDir   = Join-Path $env:ProgramData 'multiSSH'
$UserInstallDir   = Join-Path $env:LOCALAPPDATA 'multiSSH'
$UserStateDir     = Join-Path $UserInstallDir 'state'

# ------------------------------------------------------------- functions
#
# All of them, before anything that runs. PowerShell executes a function
# definition as a statement, so a function called from a block placed above its
# definition is simply not defined yet -- which is how -Rollback came to fail
# with "the term 'Restart-Agent' is not recognized".

# Write-Error would be turned into a terminating error by the preference above,
# so the exit code would come from the error rather than from here.
function Die($m) {
    Write-Host "error: $m" -ForegroundColor Red
    exit 1
}

# Compared by SID, not by name: the account is called "NT AUTHORITY\SYSTEM" in
# English and something else on every other Windows language.
function Test-System {
    return [Security.Principal.WindowsIdentity]::GetCurrent().User.Value -eq 'S-1-5-18'
}

function Test-Admin {
    $id = [Security.Principal.WindowsIdentity]::GetCurrent()
    $p  = New-Object Security.Principal.WindowsPrincipal($id)
    return $p.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
}

function Get-Manifest {
    if (Test-Path $Manifest) { return Get-Content $Manifest -Raw | ConvertFrom-Json }
    return $null
}

# A machine-wide install is a real service; a user install is a scheduled task,
# because creating a service needs administrator rights the user does not have.
# The agent detects which it is on its own, so one binary serves both.
$ServiceName = 'multissh-agent'
# The one-shot task that performs a restart from outside the session.
$RestartTaskName = 'multiSSH agent restart'

function Stop-Agent {
    if ($Scope -eq 'system') {
        Stop-Service -Name $ServiceName -Force -ErrorAction SilentlyContinue
    }
    # Also the task, always. A machine installed before the system scope became
    # a service is running one, and an uninstaller that only knew about
    # services would take away the binary and leave the task behind, still
    # scheduled, pointing at a file that no longer exists.
    Stop-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue
}

# Find-AgentProcesses locates a running agent by the exact binary it was
# started from.
#
# By path, not by name: both scopes run a process called multissh-agent, and
# uninstalling one must not take down the other. Must be called before the
# binary is renamed aside, after which nothing can be matched to it.
function Find-AgentProcesses($binary) {
    Get-Process -Name 'multissh-agent' -ErrorAction SilentlyContinue |
        Where-Object { try { $_.Path -eq $binary } catch { $false } }
}

function Remove-AgentTask {
    if ($Scope -eq 'system') {
        Stop-Service -Name $ServiceName -Force -ErrorAction SilentlyContinue
        # sc.exe rather than Remove-Service, which only exists in PowerShell 6+
        # and this may well be Windows PowerShell 5.1.
        & sc.exe delete $ServiceName 2>$null | Out-Null
    }
    Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false -ErrorAction SilentlyContinue
}

# Start-Agent registers the task and starts it.
#
# Register-ScheduledTask rather than schtasks.exe: schtasks caps the whole /TR
# command line at 261 characters and the real argument list here is over 350,
# so it failed outright -- at the very last step, on a machine that had already
# enrolled. It also cannot express restart-on-failure, and leaves the default
# three-day execution time limit in place, which would have killed the agent
# after three days with nothing to say why.
function Start-Agent($argline) {
    if ($Scope -eq 'system') {
        # A service, started at boot as LocalSystem, restarted by the service
        # manager if it ever dies. The registry holds the command line, so
        # none of schtasks' 261-character limit applies here either.
        $bin = "`"$Binary`" $argline"
        if (Get-Service -Name $ServiceName -ErrorAction SilentlyContinue) {
            & sc.exe config $ServiceName binPath= "$bin" start= auto | Out-Null
        } else {
            New-Service -Name $ServiceName -BinaryPathName $bin `
                -DisplayName 'multiSSH agent' -StartupType Automatic `
                -Description 'Reverse SSH agent: dials out to the multiSSH proxy and holds the connection open.' | Out-Null
        }
        # Restart on failure, forever. New-Service cannot express this.
        & sc.exe failure $ServiceName reset= 0 actions= restart/5000/restart/5000/restart/30000 | Out-Null
        Start-Service -Name $ServiceName
        return
    }

    $action = New-ScheduledTaskAction -Execute $Binary -Argument $argline
    $settings = New-ScheduledTaskSettingsSet `
        -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries -StartWhenAvailable `
        -MultipleInstances IgnoreNew `
        -ExecutionTimeLimit ([TimeSpan]::Zero) `
        -RestartCount 3 -RestartInterval (New-TimeSpan -Minutes 1)

    if ($Scope -eq 'system') {
        Die 'internal error: the system scope installs a service, not a task'
    } else {
        # At logon, as you. Registering a task for yourself needs no
        # administrator, and the agent then has your profile, your PATH and
        # your per-user applications.
        $me = "$env:USERDOMAIN\$env:USERNAME"
        $trigger   = New-ScheduledTaskTrigger -AtLogOn -User $me
        $principal = New-ScheduledTaskPrincipal -UserId $me `
            -LogonType Interactive -RunLevel Limited
    }

    Register-ScheduledTask -TaskName $TaskName -Action $action -Trigger $trigger `
        -Principal $principal -Settings $settings -Force | Out-Null
    Start-ScheduledTask -TaskName $TaskName
}

# Restarting the agent cannot be done from here, and that has taken three
# attempts to get right.
#
# Doing it inline -- stop, then start -- fails because this script runs inside a
# session hosted by the very process being stopped: the stop takes the script
# with it, after the binary has been swapped and before anything has been
# started again, leaving the machine installed, registered and not running.
#
# Scheduling a one-shot task fails too, but only sometimes and only from here:
# Register-ScheduledTask called from inside that session is refused with
# 0x80070005, while the same call from an ordinary shell succeeds. So it is
# tried first and must not be relied on.
#
# What is left needs no privileges at all: end the agent abruptly and let
# whatever supervises it put it back. A service has failure actions configured
# at install (restart after five seconds); the user-scope task has
# restart-on-failure. A clean stop would not trigger either -- it has to look
# like a crash, which is precisely what killing it is.
function Try-ScheduleRestart {
    try {
        $inner = "& ([scriptblock]::Create((Get-Content '$StateDir\manage.ps1' -Raw))) -StartOnly"
        $enc = [Convert]::ToBase64String([Text.Encoding]::Unicode.GetBytes($inner))

        $action = New-ScheduledTaskAction -Execute 'powershell.exe' `
            -Argument "-NoProfile -NonInteractive -WindowStyle Hidden -EncodedCommand $enc"
        $trigger = New-ScheduledTaskTrigger -Once -At (Get-Date).AddSeconds(5)
        $settings = New-ScheduledTaskSettingsSet -StartWhenAvailable `
            -ExecutionTimeLimit (New-TimeSpan -Minutes 10)

        if ($Scope -eq 'system') {
            $principal = New-ScheduledTaskPrincipal -UserId 'SYSTEM' `
                -LogonType ServiceAccount -RunLevel Highest
        } else {
            $me = "$env:USERDOMAIN\$env:USERNAME"
            $principal = New-ScheduledTaskPrincipal -UserId $me -LogonType Interactive -RunLevel Limited
        }

        Register-ScheduledTask -TaskName $RestartTaskName -Action $action -Trigger $trigger `
            -Principal $principal -Settings $settings -Force -ErrorAction Stop | Out-Null
        return $true
    } catch {
        return $false
    }
}

function Restart-Agent($argline) {
    if (Try-ScheduleRestart) {
        Write-Host "the agent will restart in a few seconds"
        return
    }

    Write-Host "could not schedule a restart from inside this session; ending the"
    Write-Host "agent instead and letting its supervisor bring it back."

    $running = @(Find-AgentProcesses $Binary)
    if ($running.Count -eq 0) {
        # Nothing to end. Starting it here is safe precisely because there is
        # no session of its own to lose.
        Start-Agent $argline
        return
    }
    # Everything is already committed -- binary swapped, manifest written -- so
    # it does not matter that this also ends the session running these lines.
    $running | Stop-Process -Force -ErrorAction SilentlyContinue
}

function Expected-Hash {
    foreach ($pair in $Hashes -split ' ') {
        $p, $h = $pair -split ':', 2
        if ($p -eq 'windows-amd64') { return $h }
    }
    return $null
}

# Replaces the agent without stopping it first, matching install.sh.
#
# Windows will not let a running .exe be overwritten, but it will let one be
# renamed. So the outgoing binary is renamed aside and the new one takes its
# place; the running process is undisturbed and only the restart at the end
# interrupts anything. An update driven over the agent's own tunnel therefore
# cannot leave the machine with no agent at all.
function Download-Binary {
    $want = Expected-Hash
    if (-not $want) { Die 'the proxy has no agent build for windows-amd64' }
    New-Item -ItemType Directory -Force -Path $InstallDir | Out-Null
    $new = "$Binary.new"
    Write-Host "downloading agent $Version for windows-amd64"
    Invoke-WebRequest -Uri "$BaseUrl/dist/windows-amd64" -OutFile $new -UseBasicParsing
    $got = (Get-FileHash $new -Algorithm SHA256).Hash.ToLower()
    if ($got -ne $want.ToLower()) {
        Remove-Item $new -Force
        Die "checksum mismatch: expected $want, got $got"
    }
    if (Test-Path $Binary) {
        Remove-Item -Force "$Binary.prev" -ErrorAction SilentlyContinue
        Move-Item -Force $Binary "$Binary.prev"
    }
    Move-Item -Force $new $Binary

    # Strip the Mark of the Web. Invoke-WebRequest tags what it downloads as
    # having come from the internet, and that tag is what pushes SmartScreen
    # and Smart App Control from "unknown" to "blocked". A freshly installed
    # agent survived it; every updated one was a new unrecognised file again.
    Unblock-File -Path $Binary -ErrorAction SilentlyContinue
}

# Key files must be plain ASCII. Set-Content's default encoding differs between
# Windows PowerShell and PowerShell 7, and a byte-order mark in front of an
# ssh-ed25519 line makes the agent fail to parse its own certificate with a
# message that points nowhere near the cause.
# Invoke-Agent runs the agent and collects its output.
#
# `& $Binary` will not do: the Windows agent is linked as a GUI-subsystem
# binary so that it never opens a console window, and PowerShell neither waits
# for nor captures the output of a GUI application -- it returns immediately
# with nothing, which read as "the agent could not generate its keys".
# Start-Process waits and redirects whatever the subsystem.
#
# The argument string is quoted here rather than passed as an array, because
# Windows PowerShell does not quote array elements for you and these paths sit
# under a user profile: "C:\Users\Firstname Lastname\AppData\..." would
# otherwise arrive as two arguments.
function Invoke-Agent($argstring) {
    $out = [IO.Path]::GetTempFileName()
    $err = [IO.Path]::GetTempFileName()
    try {
        $p = Start-Process -FilePath $Binary -ArgumentList $argstring `
            -Wait -PassThru -NoNewWindow `
            -RedirectStandardOutput $out -RedirectStandardError $err
        return @{
            Code = $p.ExitCode
            Out  = @(Get-Content $out -ErrorAction SilentlyContinue)
            Err  = (Get-Content $err -Raw -ErrorAction SilentlyContinue)
        }
    } finally {
        Remove-Item $out, $err -Force -ErrorAction SilentlyContinue
    }
}

# Smart App Control blocks executables it cannot attribute to a known
# publisher. The agent is not code signed -- signing needs a certificate this
# project does not have -- so on a machine with it enforced the agent will be
# stopped from starting, with Task Scheduler reporting 0x800704C7
# (ERROR_CANCELLED) and nothing anywhere saying why.
#
# Worth reporting rather than letting it be discovered as a machine that
# quietly stops coming back after an update.
function Get-SmartAppControlState {
    try {
        $v = (Get-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\CI\Policy' `
              -Name 'VerifiedAndReputablePolicyState' -ErrorAction Stop).VerifiedAndReputablePolicyState
        switch ($v) {
            0 { 'off' }
            1 { 'enforced' }
            2 { 'evaluation' }
            default { "unknown ($v)" }
        }
    } catch {
        'off'   # the value is absent on Windows 10 and Server, where there is no such thing
    }
}

function Warn-IfBlocked {
    $sac = Get-SmartAppControlState
    if ($sac -eq 'off') { return }
    Write-Host ""
    Write-Host "  NOTE: Smart App Control is $sac on this machine." -ForegroundColor Yellow
    Write-Host "  The agent is not code signed, so it may be blocked from starting."
    Write-Host "  A blocked start shows up as scheduled task result 0x800704C7 and an"
    Write-Host "  agent that never reconnects. If that happens, either exclude"
    Write-Host "    $Binary"
    Write-Host "  in Windows Security, or turn Smart App Control off (Settings ->"
    Write-Host "  Privacy & security -> Windows Security -> App & browser control)."
    Write-Host ""
}

function Write-KeyFile($path, $content) {
    Set-Content -Path $path -Value $content -Encoding ascii -NoNewline
}

# ------------------------------------------------------------- scope

$elevated = Test-Admin

# Scope follows elevation, exactly as install.sh follows uid: an elevated shell
# installs for the machine, anyone else installs for themselves. -Scope forces
# either.
#
# Deliberately not cleverer than that. An earlier version also consulted which
# manifests already existed, which produced a dead end -- an unelevated run on a
# machine that already had a system install resolved to "system" and then
# refused itself, when what the person plainly wanted was their own.
if (-not $Scope) {
    if ($elevated) { $Scope = 'system' } else { $Scope = 'user' }
}

# A user install run *by SYSTEM* would install into SYSTEM's own profile, which
# is not a user in any sense that helps: same absent PATH, same missing winget,
# just a second agent with none of the point of the first. The likely way to
# arrive here is through a multiSSH session on this very machine, where the
# shell is SYSTEM -- so say so, since from inside that session it looks exactly
# like an ordinary elevated prompt.
if ($Scope -eq 'user' -and (Test-System)) {
    Die @"
this shell is running as SYSTEM, so a user install would be installed for
SYSTEM -- the same profile the existing agent already has, and none of the
per-user tools you are presumably after.

A user-scope agent has to be installed by the user it will run as. Log in to
this machine as that person and run the installer from their own PowerShell.
"@
}

if ($Scope -eq 'system') {
    if (-not $elevated) {
        Die 'a system install needs an elevated PowerShell (Run as Administrator), or pass -Scope user to install for yourself'
    }
    $InstallDir = $SystemInstallDir
    $StateDir   = $SystemStateDir
    # Kept even though the system scope installs a service now: it is the name
    # a pre-service install used, and uninstall still has to find it.
    $TaskName   = 'multiSSH agent'
} else {
    $InstallDir = $UserInstallDir
    $StateDir   = $UserStateDir
    # A distinct name: scheduled tasks share one namespace across the machine,
    # so a user install must not collide with the SYSTEM one. Both are meant to
    # be able to exist at once.
    $TaskName   = "multiSSH agent ($env:USERNAME)"
}
$Binary   = Join-Path $InstallDir 'multissh-agent.exe'
$Manifest = Join-Path $StateDir 'manifest.json'

# ------------------------------------------------------------- start only

# Invoked by the one-shot task above, and by nothing else. Does the stop and
# start that the update could not safely do itself, then removes the task that
# ran it.
if ($StartOnly) {
    $m = Get-Manifest
    if (-not $m) { Die "nothing installed here (no $Manifest)" }
    Stop-Agent
    Start-Agent $m.args
    Unregister-ScheduledTask -TaskName $RestartTaskName -Confirm:$false -ErrorAction SilentlyContinue
    exit 0
}

# ------------------------------------------------------------- uninstall

if ($Uninstall) {
    $m = Get-Manifest
    if (-not $m) { Die "nothing installed here (no $Manifest)" }
    Write-Host "will remove:"
    Write-Host "  $($m.binary)"
    Write-Host "  $($m.state)  (identity key, host key, certificate)"
    Write-Host "  scheduled task '$TaskName'"
    if (-not $Yes) {
        $c = Read-Host 'remove, including the keys? [y/N]'
        if ($c -notmatch '^[yY]') { Write-Host 'cancelled'; exit 0 }
    }
    # Ordered so that an uninstall driven over the agent's own tunnel finishes:
    # ending the task kills this script with it, so everything that can be done
    # while the agent still runs is done first. Windows refuses to delete a
    # running .exe but allows it to be renamed, so the binary is moved aside
    # and only then deleted.
    # Noted before anything moves, and killed at the very end.
    #
    # Unregistering a task does not stop an instance of it that is already
    # running -- it only removes the definition. So the old order took the
    # definition away and then asked Task Scheduler to stop a task it no longer
    # knew about, which did nothing, and left the agent running with its keys
    # deleted underneath it: gone from Get-ScheduledTask, still connected to
    # the proxy, still listed as online, and unable to serve a session.
    $running = @(Find-AgentProcesses $m.binary)

    Remove-AgentTask
    Unregister-ScheduledTask -TaskName $RestartTaskName -Confirm:$false -ErrorAction SilentlyContinue
    Remove-Item -Recurse -Force $m.state -ErrorAction SilentlyContinue
    if (Test-Path $m.binary) {
        Move-Item -Force $m.binary "$($m.binary).removing" -ErrorAction SilentlyContinue
    }
    Remove-Item -Force "$($m.binary).prev", "$($m.binary).new" -ErrorAction SilentlyContinue
    Write-Host 'removed.'

    Stop-Agent
    if ($running.Count -gt 0) {
        Write-Host "stopping $($running.Count) running agent process(es)"
        $running | Stop-Process -Force -ErrorAction SilentlyContinue
    }
    Remove-Item -Recurse -Force $InstallDir -ErrorAction SilentlyContinue
    exit 0
}

# ------------------------------------------------------------- rollback

if ($Rollback) {
    $m = Get-Manifest
    if (-not $m) { Die "nothing installed here (no $Manifest)" }
    if (-not (Test-Path "$Binary.prev")) { Die "no previous binary saved at $Binary.prev" }
    Copy-Item -Force "$Binary.prev" "$Binary.rollback"
    Move-Item -Force "$Binary.rollback" $Binary
    # The recorded version no longer describes what is on disk, so clear it or
    # the next -Update would decide there was nothing to do.
    $m.version = 'rolled-back'
    $m | ConvertTo-Json | Set-Content $Manifest
    Restart-Agent $m.args
    Write-Host 'rolled back to the previous binary; run -Update to go forward again'
    exit 0
}

# ------------------------------------------------------------- update

# This copy has the proxy's version frozen into it from install time and the
# manifest holds that same value, so comparing them here would always report
# "already current". Fetch what the proxy is serving now and hand over to it.
#
# Run as a scriptblock rather than as a file: executing a downloaded .ps1 is
# subject to the execution policy, which on a default Windows install refuses
# it -- and the whole point of the piped installer is that it does not need one
# changed.
if ($Update -and -not $env:MULTISSH_NO_REFETCH -and (Test-Path $Manifest)) {
    $fetched = $null
    try {
        $fetched = (Invoke-WebRequest -Uri "$BaseUrl/install.ps1" -UseBasicParsing).Content
    } catch {
        Write-Host "could not reach $BaseUrl; continuing with this copy"
    }
    if ($fetched) {
        $env:MULTISSH_NO_REFETCH = '1'
        try {
            & ([scriptblock]::Create($fetched)) -Update -Yes:$Yes
        } finally {
            Remove-Item Env:\MULTISSH_NO_REFETCH -ErrorAction SilentlyContinue
        }
        exit 0
    }
}

$existing = Get-Manifest
if ($existing -and -not $Reenroll) {
    if (-not $Update) {
        Write-Host "already installed here ($($existing.canonical)); updating instead."
        Write-Host "pass -Reenroll to discard that identity and enrol afresh."
    }
    if ($existing.ca -ne $CaKey) { Die 'this proxy has a different authority than the one enrolled with; refusing' }
    if ($existing.version -eq $Version) { Write-Host "already current ($Version)"; exit 0 }
    Download-Binary
    $existing.version = $Version
    $existing | ConvertTo-Json | Set-Content $Manifest
    Restart-Agent $existing.args
    Write-Host "updated to $Version; keys and certificate untouched"
    Warn-IfBlocked
    exit 0
}

# ------------------------------------------------------------- install

if (-not $Name) {
    $default = ($env:COMPUTERNAME).ToLower() -replace '[^a-z0-9-]', '-'

    # When the other scope is already installed on this machine, steer the
    # default name away from the one it holds. Two agents can both ask for a
    # friendly name but only one can have it, so the second would be reachable
    # under its canonical name alone -- correct, and quietly baffling.
    #
    # The other scope's *task* is the thing to look for, not its manifest: a
    # system install's state directory is locked to SYSTEM and Administrators,
    # so an unelevated shell cannot see it at all.
    $otherTask = if ($Scope -eq 'system') { "multiSSH agent ($env:USERNAME)" }
                 else                     { 'multiSSH agent' }
    if (Get-ScheduledTask -TaskName $otherTask -ErrorAction SilentlyContinue) {
        $default = "$default-$Scope"
        Write-Host "note: this machine already has a $(if ($Scope -eq 'system') { 'user' } else { 'system' })-scope agent,"
        Write-Host "      so the suggested name avoids the one it holds."
    }

    if ($Yes) { $Name = $default }
    else {
        $Name = Read-Host "name for this machine [$default]"
        if (-not $Name) { $Name = $default }
    }
}

Write-Host ""
Write-Host "  install to   $Binary"
Write-Host "  state in     $StateDir"
# The scope is named, not merely implied by its consequences. It was chosen for
# you from whether this shell is elevated, so the summary has to say which way
# that went and how to get the other -- otherwise the only way to find out is
# to finish the install and notice what you ended up with.
if ($Scope -eq 'system') {
    Write-Host "  scope        system, a Windows service running as LocalSystem"
    Write-Host "  reachable    always, including before anyone logs in"
    Write-Host "  note         no user profile: winget and other per-user tools"
    Write-Host "               are not on SYSTEM's PATH"
} else {
    Write-Host "  scope        user, as $env:USERNAME, started at logon"
    Write-Host "  reachable    only while you are logged in"
    if (-not $elevated) {
        Write-Host "               (chosen because this shell is not elevated;"
        Write-Host "                run as Administrator for a system install)"
    }
}
Write-Host "  proxy        $Proxies"
Write-Host "  name         $Name"
Write-Host ""

if (-not $Yes) {
    $c = Read-Host 'proceed? [Y/n]'
    if ($c -match '^[nN]') { Write-Host 'cancelled'; exit 0 }
}

if (-not $Password) { $Password = $env:MULTISSH_PASSWORD }
if (-not $Password) {
    $sec = Read-Host 'enrollment password' -AsSecureString
    $Password = [Runtime.InteropServices.Marshal]::PtrToStringAuto(
        [Runtime.InteropServices.Marshal]::SecureStringToBSTR($sec))
}
if (-not $Password) { Die 'a password is required' }

New-Item -ItemType Directory -Force -Path $StateDir | Out-Null
if ($Scope -eq 'system') {
    # Keys and certificate are readable only by SYSTEM and Administrators.
    icacls $StateDir /inheritance:r /grant 'SYSTEM:(OI)(CI)F' /grant 'Administrators:(OI)(CI)F' | Out-Null
}
# A user install lives under LOCALAPPDATA, which is already private to you --
# and a local administrator could read it either way, exactly as on Linux.

Download-Binary

# The agent generates its own keys, so no ssh-keygen is needed -- a stock
# Windows install may not have one. Private halves never leave the machine.
$idPath   = Join-Path $StateDir 'agent_identity'
$hostPath = Join-Path $StateDir 'agent_host_key'
$r = Invoke-Agent ('-show-keys -identity "{0}" -host-key "{1}"' -f $idPath, $hostPath)
if ($r.Code -ne 0) { Die "the agent could not generate its keys: $($r.Err)" }
$keys = $r.Out

$identityKey = ($keys | Where-Object { $_ -like 'identity *' } | Select-Object -First 1) -replace '^identity ', ''
$hostKey     = ($keys | Where-Object { $_ -like 'host *' }     | Select-Object -First 1) -replace '^host ', ''
if (-not $identityKey -or -not $hostKey) {
    Die "unexpected output from -show-keys; got: $keys"
}

Write-Host 'enrolling...'
$body = @{
    password     = $Password
    name         = $Name
    identity_key = $identityKey
    host_key     = $hostKey
    version      = $Version
    platform     = 'windows-amd64'
} | ConvertTo-Json

try {
    $resp = Invoke-RestMethod -Uri "$BaseUrl/enroll" -Method Post -Body $body `
        -ContentType 'application/json' -UseBasicParsing
} catch {
    Die "enrolment refused (wrong or expired password?): $($_.Exception.Message)"
}

Write-KeyFile (Join-Path $StateDir 'agent_identity-cert.pub') $resp.certificate
Write-KeyFile (Join-Path $StateDir 'proxy_ca.pub')            $resp.ca
Write-KeyFile (Join-Path $StateDir 'agent_authorized_keys')   $resp.authorized_keys

# The Windows agent is linked as a GUI binary, so that a user-scope install
# does not put a console window on the desktop for somebody to close -- which
# killed the agent with it. That leaves no usable stderr, so the log has to go
# to a file, and -log is not optional here.
$logPath = Join-Path $StateDir 'agent.log'

$argline = "-proxy $Proxies -log `"$logPath`" -identity `"$idPath`" -host-key `"$hostPath`" " +
           "-identity-cert `"$(Join-Path $StateDir 'agent_identity-cert.pub')`" " +
           "-ca `"$(Join-Path $StateDir 'proxy_ca.pub')`" " +
           "-authorized-keys `"$(Join-Path $StateDir 'agent_authorized_keys')`""

@{
    version   = $Version
    binary    = $Binary
    state     = $StateDir
    scope     = $Scope
    platform  = 'windows-amd64'
    proxy     = $Proxies
    ca        = $CaKey
    canonical = $resp.canonical
    args      = $argline
    installed = (Get-Date).ToUniversalTime().ToString('o')
} | ConvertTo-Json | Set-Content $Manifest

# Keep a copy so update and uninstall work when the proxy is gone.
try { Invoke-WebRequest -Uri "$BaseUrl/install.ps1" -OutFile (Join-Path $StateDir 'manage.ps1') -UseBasicParsing } catch {}

Start-Agent $argline

Write-Host ""
Warn-IfBlocked
Write-Host "  installed and running"
Write-Host ""
Write-Host "  canonical  $($resp.canonical)   always works"
Write-Host "  friendly   $($resp.friendly)   yours unless another machine already holds it"
Write-Host ""
Write-Host "  ssh -J <proxy> anything@$($resp.friendly)"
if ($Scope -eq 'system') {
    Write-Host "  (the username is ignored; the shell runs as SYSTEM, so per-user"
    Write-Host "   tools such as winget are not on its PATH)"
} else {
    Write-Host "  (the username is ignored; the shell runs as $env:USERNAME)"
}
Write-Host ""
Write-Host "  log        $StateDir\agent.log"
Write-Host ""
Write-Host "  update, roll back or remove:"
Write-Host "    `$m = '$StateDir\manage.ps1'"
Write-Host "    & ([scriptblock]::Create((Get-Content `$m -Raw))) -Update"
Write-Host "    & ([scriptblock]::Create((Get-Content `$m -Raw))) -Rollback"
Write-Host "    & ([scriptblock]::Create((Get-Content `$m -Raw))) -Uninstall"
Write-Host ""
