#!/bin/sh
# multiSSH agent installer.
#
# Generated by the proxy, which bakes in its own certificate authority and
# address below. That is deliberate: the agent pins the right authority from
# its first connect, anchored on the TLS certificate you fetched this over,
# so there is no trust-on-first-use window for the agent-to-proxy hop.
#
# A copy of this script and a manifest of what it installed are saved next to
# the agent, so update and uninstall keep working when the proxy is gone.
set -eu

BASE_URL='__BASE_URL__'
PROXIES='__PROXIES__'
CA_KEY='__CA__'
VERSION='__VERSION__'
HASHES='__HASHES__'

MODE=install
REENROLL=
ASSUME_YES=${MULTISSH_YES:-}

for arg in "$@"; do
    case "$arg" in
        --uninstall) MODE=uninstall ;;
        --update)    MODE=update ;;
        -y|--yes)    ASSUME_YES=1 ;;
        --reenroll)  REENROLL=1 ;;
        -h|--help)
            cat <<EOF
multiSSH agent installer

  sh install.sh              install and enrol this machine
  sh install.sh --update     replace the binary, keep keys and certificate
  sh install.sh --uninstall  stop and remove everything

  -y, --yes                  accept defaults, do not prompt
      --reenroll             force a fresh enrolment over an existing install

Piped from curl, pass options after '--':
  curl -fsSL $BASE_URL/install.sh | sudo sh -s -- --uninstall

Non-interactive installs read: MULTISSH_PASSWORD (required), MULTISSH_NAME,
MULTISSH_PROXY, MULTISSH_PREFIX, MULTISSH_STATE_DIR, MULTISSH_SCOPE.
EOF
            exit 0 ;;
        *) echo "unknown option: $arg (try --help)" >&2; exit 2 ;;
    esac
done

die() { echo "error: $*" >&2; exit 1; }
have() { command -v "$1" >/dev/null 2>&1; }

# stdin is the script itself when piped from curl, so prompts must read the
# terminal directly. When there is no terminal at all, run unattended rather
# than hang on a question nobody can answer.
INTERACTIVE=1
[ -r /dev/tty ] && [ -z "$ASSUME_YES" ] || INTERACTIVE=
ask() { # ask VAR "prompt" "default"
    _d=$3
    if [ -n "$INTERACTIVE" ]; then
        printf '%s [%s]: ' "$2" "$_d" > /dev/tty
        read -r _a < /dev/tty || _a=
        [ -n "$_a" ] || _a=$_d
    else
        _a=$_d
    fi
    eval "$1=\$_a"
}
ask_secret() { # ask_secret VAR "prompt"
    if [ -n "${MULTISSH_PASSWORD:-}" ]; then eval "$1=\$MULTISSH_PASSWORD"; return; fi
    [ -n "$INTERACTIVE" ] || die "no terminal; set MULTISSH_PASSWORD"
    printf '%s: ' "$2" > /dev/tty
    stty -echo < /dev/tty 2>/dev/null || true
    read -r _s < /dev/tty || _s=
    stty echo < /dev/tty 2>/dev/null || true
    printf '\n' > /dev/tty
    eval "$1=\$_s"
}

# ---------------------------------------------------------------- platform

case "$(uname -s)" in
    Linux)  OS=linux ;;
    Darwin) OS=darwin ;;
    *) die "unsupported system: $(uname -s)" ;;
esac
case "$(uname -m)" in
    x86_64|amd64)  ARCH=amd64 ;;
    aarch64|arm64) ARCH=arm64 ;;
    *) die "unsupported architecture: $(uname -m)" ;;
esac
PLATFORM="$OS-$ARCH"

# Scope follows reality: root installs system-wide, anyone else installs for
# themselves, because a system install would only fail later.
if [ "$(id -u)" = 0 ]; then SCOPE=${MULTISSH_SCOPE:-system}; else SCOPE=${MULTISSH_SCOPE:-user}; fi
if [ "$SCOPE" = system ] && [ "$(id -u)" != 0 ]; then
    die "a system install needs root; re-run with sudo, or let it default to a user install"
fi

if [ "$SCOPE" = system ]; then
    PREFIX=${MULTISSH_PREFIX:-/usr/local/bin}
    if [ "$OS" = darwin ]; then
        STATE=${MULTISSH_STATE_DIR:-/Library/Application Support/multissh-agent}
    else
        STATE=${MULTISSH_STATE_DIR:-/var/lib/multissh-agent}
    fi
else
    PREFIX=${MULTISSH_PREFIX:-$HOME/.local/bin}
    STATE=${MULTISSH_STATE_DIR:-$HOME/.config/multissh-agent}
fi
BIN="$PREFIX/multissh-agent"
MANIFEST="$STATE/manifest"

# An existing manifest is authoritative about where this machine put things,
# which a freshly fetched script could not know if the paths were customised.
if [ -f "$MANIFEST" ]; then
    # shellcheck disable=SC1090
    . "$MANIFEST"
    BIN=$M_BIN; STATE=$M_STATE; SCOPE=$M_SCOPE
    MANIFEST="$STATE/manifest"
fi

svc_name() { echo multissh-agent; }
svc_stop() {
    case "$OS-$SCOPE" in
        linux-system) systemctl stop "$(svc_name)" 2>/dev/null || true ;;
        linux-user)   systemctl --user stop "$(svc_name)" 2>/dev/null || true ;;
        darwin-*)     launchctl bootout system/net.multissh.agent 2>/dev/null || true ;;
    esac
}
svc_start() {
    case "$OS-$SCOPE" in
        linux-system) systemctl daemon-reload; systemctl enable --now "$(svc_name)" ;;
        linux-user)   systemctl --user daemon-reload; systemctl --user enable --now "$(svc_name)" ;;
        darwin-*)     launchctl bootstrap system "$PLIST" 2>/dev/null || launchctl load "$PLIST" ;;
    esac
}

# ---------------------------------------------------------------- uninstall

if [ "$MODE" = uninstall ]; then
    [ -f "$MANIFEST" ] || die "nothing installed here (no $MANIFEST)"
    echo "will remove:"
    echo "  $BIN"
    echo "  $STATE  (identity key, host key, certificate)"
    echo "  the service unit"
    if [ -n "$INTERACTIVE" ]; then
        printf 'remove, including the keys? [y/N]: ' > /dev/tty
        read -r c < /dev/tty || c=
        case "$c" in y|Y|yes) ;; *) echo "cancelled"; exit 0 ;; esac
    fi
    svc_stop
    case "$OS-$SCOPE" in
        linux-system) rm -f /etc/systemd/system/multissh-agent.service; systemctl daemon-reload 2>/dev/null || true ;;
        linux-user)   rm -f "$HOME/.config/systemd/user/multissh-agent.service"; systemctl --user daemon-reload 2>/dev/null || true ;;
        darwin-*)     rm -f /Library/LaunchDaemons/net.multissh.agent.plist ;;
    esac
    rm -f "$BIN"
    rm -rf "$STATE"
    echo "removed."
    exit 0
fi

# Re-running the installer on a machine that already has one should update it,
# not enrol it a second time under a new identity. Enrolling again would leave
# the old certificate valid and the old name occupied.
if [ "$MODE" = install ] && [ -f "$MANIFEST" ] && [ -z "$REENROLL" ]; then
    echo "already installed here (${M_CANONICAL:-unknown}); updating instead."
    echo "pass --reenroll to discard that identity and enrol afresh."
    MODE=update
fi

# ---------------------------------------------------------------- download

fetch() { # fetch URL DEST
    if have curl; then curl -fsSL "$1" -o "$2"
    elif have wget; then wget -qO "$2" "$1"
    else die "need curl or wget"; fi
}

# Must always exit zero. Under 'set -e' a non-zero status here aborts the whole
# script, and a loop that ends on a non-matching entry would do exactly that --
# which stayed hidden while only one build existed and the match came last.
expected_hash() {
    for _pair in $HASHES; do
        case "$_pair" in
            "$PLATFORM":*) echo "${_pair#*:}"; return 0 ;;
        esac
    done
    return 0
}

sha256_of() {
    if have sha256sum; then sha256sum "$1" | cut -d' ' -f1
    elif have shasum; then shasum -a 256 "$1" | cut -d' ' -f1
    else echo ""; fi
}

download_binary() {
    WANT=$(expected_hash)
    [ -n "$WANT" ] || die "the proxy has no agent build for $PLATFORM"
    TMP=$(mktemp)
    echo "downloading agent $VERSION for $PLATFORM"
    fetch "$BASE_URL/dist/$PLATFORM" "$TMP" || die "download failed"
    GOT=$(sha256_of "$TMP")
    if [ -n "$GOT" ] && [ "$GOT" != "$WANT" ]; then
        rm -f "$TMP"; die "checksum mismatch: expected $WANT, got $GOT"
    fi
    mkdir -p "$PREFIX"
    svc_stop
    mv "$TMP" "$BIN"
    chmod 0755 "$BIN"
}

# ---------------------------------------------------------------- update

if [ "$MODE" = update ]; then
    [ -f "$MANIFEST" ] || die "nothing installed here (no $MANIFEST)"
    [ "$M_CA" = "$CA_KEY" ] || die "this proxy has a different authority than the one enrolled with; refusing"
    if [ "$M_VERSION" = "$VERSION" ]; then echo "already current ($VERSION)"; exit 0; fi
    download_binary
    sed -i.bak "s|^M_VERSION=.*|M_VERSION='$VERSION'|" "$MANIFEST" 2>/dev/null || true
    rm -f "$MANIFEST.bak"
    svc_start
    echo "updated to $VERSION; keys and certificate untouched"
    exit 0
fi

# ---------------------------------------------------------------- install

DEFAULT_NAME=$(hostname 2>/dev/null || echo machine)
DEFAULT_NAME=$(echo "$DEFAULT_NAME" | tr '[:upper:]' '[:lower:]' | sed 's/\..*//; s/[^a-z0-9-]/-/g')
ask NAME "name for this machine" "${MULTISSH_NAME:-$DEFAULT_NAME}"
PROXY_LIST=${MULTISSH_PROXY:-$PROXIES}

cat <<EOF

  install to   $BIN
  state in     $STATE
  scope        $SCOPE
  proxy        $PROXY_LIST
  name         $NAME

EOF

if [ -n "$INTERACTIVE" ]; then
    printf 'proceed? [Y/n/c=customise]: ' > /dev/tty
    read -r c < /dev/tty || c=
    case "$c" in
        n|N) echo "cancelled"; exit 0 ;;
        c|C)
            ask PREFIX "install directory" "$PREFIX"
            ask STATE  "state directory"   "$STATE"
            ask PROXY_LIST "proxy url(s), comma separated" "$PROXY_LIST"
            BIN="$PREFIX/multissh-agent"; MANIFEST="$STATE/manifest" ;;
    esac
fi

ask_secret PASSWORD "enrollment password"
[ -n "$PASSWORD" ] || die "a password is required"

mkdir -p "$STATE"
chmod 0700 "$STATE"
download_binary

# Private keys are generated here and never leave the machine; only the public
# halves are sent for signing.
have ssh-keygen || die "need ssh-keygen"
[ -f "$STATE/agent_identity" ]  || ssh-keygen -t ed25519 -N '' -q -C "multissh-identity" -f "$STATE/agent_identity"
[ -f "$STATE/agent_host_key" ]  || ssh-keygen -t ed25519 -N '' -q -C "multissh-host"     -f "$STATE/agent_host_key"

json_escape() { printf '%s' "$1" | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g' | tr -d '\n'; }
REQ=$(printf '{"password":"%s","name":"%s","identity_key":"%s","host_key":"%s","version":"%s","platform":"%s"}' \
    "$(json_escape "$PASSWORD")" "$(json_escape "$NAME")" \
    "$(json_escape "$(cat "$STATE/agent_identity.pub")")" \
    "$(json_escape "$(cat "$STATE/agent_host_key.pub")")" \
    "$VERSION" "$PLATFORM")

echo "enrolling..."
RESP=$(printf '%s' "$REQ" | curl -fsSL -X POST -H 'Content-Type: application/json' --data-binary @- "$BASE_URL/enroll") \
    || die "enrolment refused (wrong or expired password?)"

field() { printf '%s' "$RESP" | sed -n "s/.*\"$1\":\"\\([^\"]*\\)\".*/\\1/p" | head -1; }
unescape() { printf '%b' "$1"; }

unescape "$(field certificate)"      > "$STATE/agent_identity-cert.pub"
unescape "$(field ca)"               > "$STATE/proxy_ca.pub"
unescape "$(field authorized_keys)"  > "$STATE/agent_authorized_keys"
CANONICAL=$(field canonical)
FRIENDLY=$(field friendly)
[ -s "$STATE/agent_identity-cert.pub" ] || die "the proxy returned no certificate"

printf 'PROXY=%s\n' "$PROXY_LIST" > "$STATE/config"
chmod 0600 "$STATE"/agent_identity "$STATE"/agent_host_key "$STATE/config"

# ---------------------------------------------------------------- service

ARGS="-proxy $PROXY_LIST -identity $STATE/agent_identity -host-key $STATE/agent_host_key -identity-cert $STATE/agent_identity-cert.pub -ca $STATE/proxy_ca.pub -authorized-keys $STATE/agent_authorized_keys"

case "$OS-$SCOPE" in
    linux-*)
        if [ "$SCOPE" = system ]; then UNIT=/etc/systemd/system/multissh-agent.service
        else UNIT="$HOME/.config/systemd/user/multissh-agent.service"; mkdir -p "$(dirname "$UNIT")"; fi
        cat > "$UNIT" <<EOF
[Unit]
Description=multiSSH agent
After=network-online.target
Wants=network-online.target

[Service]
ExecStart=$BIN $ARGS
Restart=always
RestartSec=5
LimitNOFILE=65535
WorkingDirectory=$STATE

[Install]
WantedBy=$( [ "$SCOPE" = system ] && echo multi-user.target || echo default.target )
EOF
        ;;
    darwin-*)
        PLIST=/Library/LaunchDaemons/net.multissh.agent.plist
        cat > "$PLIST" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0"><dict>
  <key>Label</key><string>net.multissh.agent</string>
  <key>ProgramArguments</key><array>
    <string>$BIN</string>$(for a in $ARGS; do printf '<string>%s</string>' "$a"; done)
  </array>
  <key>RunAtLoad</key><true/>
  <key>KeepAlive</key><true/>
</dict></plist>
EOF
        ;;
esac

cat > "$MANIFEST" <<EOF
# multiSSH agent install manifest -- read by --update and --uninstall
M_VERSION='$VERSION'
M_BIN='$BIN'
M_STATE='$STATE'
M_SCOPE='$SCOPE'
M_PLATFORM='$PLATFORM'
M_PROXY='$PROXY_LIST'
M_CA='$CA_KEY'
M_CANONICAL='$CANONICAL'
M_INSTALLED='$(date -u +%Y-%m-%dT%H:%M:%SZ)'
EOF
chmod 0600 "$MANIFEST"

# Keep a copy so update and uninstall work with the proxy gone.
if [ -n "${SCRIPT_SELF:-}" ] && [ -f "$SCRIPT_SELF" ]; then
    cp "$SCRIPT_SELF" "$STATE/manage.sh"
else
    fetch "$BASE_URL/install.sh" "$STATE/manage.sh" || true
fi
chmod 0700 "$STATE/manage.sh" 2>/dev/null || true

svc_start

cat <<EOF

  installed and running

  canonical  $CANONICAL      always works
  friendly   $(printf "%-22s" "$FRIENDLY") yours unless another machine already holds it

  ssh -J <proxy> root@$FRIENDLY

  update or remove:
    sh $STATE/manage.sh --update
    sh $STATE/manage.sh --uninstall

EOF
